Yoma-499 - refactor(Organisations) - add organisations data to state
didx-xyz/yoma-mobile pull request #105
Opened 2021-08-06 05:25 UTC by sciphergfx

## Scope [YOMA-499](https://yomaworld.atlassian.net/browse/YOMA-499)

![](gifSrc)
## Work Done
add organisations data to state

2021-08-08 09:57 UTC, cameronolivier reviewed
Please delete: `src/modules/Organisations/Organisations.types.tsx` as there is nothing in it.

2021-08-08 11:12 UTC, cameronolivier requested changes

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.utils.tsx
> +export const extractOrganisationsFromPayload = path(['payload', 'data', 'data'])
I think I said this elsewhere - this (`['payload', 'data', 'data']`) is a repeated pattern - I think it's best we move it to a single util - api utils might be a good place. 
something like `extractPayloadData` should work.

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const setOrganisations = createAction<any>(`${name} setOrganisations`)
please type this correctly.

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
please type this correctly

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
Also please normalise the data as we have discussed.

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.test.tsx
> +      const mockState = rootStateFixture({})
you don't need to pass an empty object - it's set as the default already.

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.test.tsx
> +      const mockState = rootStateFixture({})
call it like `rootStateFixture()`

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.test.tsx
> +    it('should return organisations from the root state', () => {
please mock what happens with data as well.

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +export const fetchOrganisationsSuccessFlow: Middleware =
please add normalising data here as well

2021-08-08 11:12 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.test.tsx
> +      // when ... we respond to the fetchOrganisationsSuccess action
please add a line of whitespace above the //when.. and //then...

2021-08-09 11:22 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
Normalising is useful as we both want to list all - and handle selecting specific organisations - which is what normalising makes easy and trivial. 

Anywhere where we may want to both map over a list of objects AND need to access specific objects directly which is a powerful paradigm and makes working with the data a lot easier - so wherever we're handling lists of objects let's do this, please.

2021-08-11 07:43 UTC, sciphergfx commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
This approach was taken as we needed just a list of organisations for the specific ticket we were working on before the request to break the PR down further. If normalising its state data adds any layer of flexibility and speed to its current implementation/use at the UI level, happy to do it.

In order to avoid any back and forth, is the expectations here to use Object.values(theNormalisedEntity) in the UI?

2021-08-11 07:45 UTC, sciphergfx commented on src/modules/Organisations/Organisations.middleware.tsx
> +export const fetchOrganisationsSuccessFlow: Middleware =
Noted, happy to implement, i've asked a question in this regard, please see below. Thanks

2021-08-11 07:55 UTC, sciphergfx commented on src/modules/Organisations/Organisations.utils.tsx
> +export const extractOrganisationsFromPayload = path(['payload', 'data', 'data'])
Yes added util function in another PR, I'll copy here again.

2021-08-11 07:57 UTC, sciphergfx commented on src/modules/Organisations/Organisations.utils.tsx
> +export const extractOrganisationsFromPayload = path(['payload', 'data', 'data'])
Yes, added this util and used in one of the PR it was extracted from. I'll copy over

2021-08-16 21:06 UTC, cameronolivier requested changes
Please add release notes and bump the version.

2021-08-16 21:06 UTC, cameronolivier commented on src/api/api.types.ts
> -  Organisations = 'organisations',
issue: this should not be removed.

2021-08-16 21:06 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +      const normalisedOrganisations = normalise(action.payload)
as the data shape is similar to Skills, we will need to wait until the skills branch is in before merging, otherwise running normalise will break (there's no 'id' prop).

2021-08-16 21:18 UTC, sciphergfx commented on src/api/api.types.ts
> -  Organisations = 'organisations',
shot, missed. Will re-add then release notes and version bump

2021-08-18 17:34 UTC, cameronolivier requested changes

2021-08-18 17:34 UTC, cameronolivier commented on android/app/build.gradle
> +        versionCode 20
this should be bumped to 22, please. Develop is currently on 21. https://github.com/didx-xyz/yoma-mobile/blob/8a80c2ba5a4eedaec028e49e99daef02aadd8ca8/android/app/build.gradle#L143

2021-08-18 17:36 UTC, cameronolivier requested changes
You have a bunch of conflicts.

2021-08-18 20:05 UTC, cameronolivier requested changes

2021-08-18 20:05 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(OrganisationsActions.clearOrganisations())
suggestion: we shouldn't clear organisations as I don't believe they're tied to any user data.

2021-08-18 20:05 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
>        dispatch(JobActions.clearJob())
issue: Shouldn't clear jobs either

2021-08-18 20:05 UTC, cameronolivier commented on src/redux/middleware.ts
> +import { middleware as JobsMiddleware } from '../modules/Jobs'
Question: why are we adding jobs middleware in the `organisations` PR? Are you sure this is intended?

2021-08-18 21:01 UTC, sciphergfx commented on src/redux/middleware.ts
> +import { middleware as JobsMiddleware } from '../modules/Jobs'
this is in develop @cameronolivier

2021-08-18 21:02 UTC, cameronolivier commented on src/redux/middleware.ts
> +import { middleware as JobsMiddleware } from '../modules/Jobs'
I looked at 'changes since last commit' - which I presume now was a merge/ conflict fix. My bad.

2021-08-18 21:03 UTC, sciphergfx commented on src/modules/App/App.middleware.ts
>        dispatch(JobActions.clearJob())
I'm lost here, this is  a different task if i'm not mistaken? @cameronolivier

2021-08-18 21:04 UTC, sciphergfx commented on src/modules/App/App.middleware.ts
> +      dispatch(OrganisationsActions.clearOrganisations())
noted

2021-08-18 21:06 UTC, cameronolivier reviewed
Left a question as I don't think the normalising will be functional until the skills work (And adjustments to switching between 'id' and 'key' are in.

2021-08-18 21:06 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +      const normalisedOrganisations = normalise(action.payload)
question: @sciphergfx further to this - does this work? All the adjustments re normalising with 'key' prop are in the skills PR, so I don't think this will actually work yet?

2021-08-18 21:08 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
>        dispatch(JobActions.clearJob())
sorry @sciphergfx as mentioned - I filtered to see changes in last commit - but that was a merge in from develop -so it highlighted the jobs changes.

2021-08-18 21:09 UTC, sciphergfx commented on src/modules/Organisations/Organisations.middleware.tsx
> +      const normalisedOrganisations = normalise(action.payload)
ok the skills PR is ready, we can merge that, then i adjust here @cameronolivier

2021-08-18 21:10 UTC, sciphergfx commented on src/modules/Organisations/Organisations.middleware.tsx
> +      const normalisedOrganisations = normalise(action.payload)
Let me fix conflicts there

2021-08-19 13:12 UTC, cameronolivier approved these changes

2021-08-19 13:13 UTC, merged