YOMA-500 - refactor(skills): add skills to state
didx-xyz/yoma-mobile pull request #106
Opened 2021-08-06 07:28 UTC by sciphergfx

## Scope [YOMA-500](https://yomaworld.atlassian.net/browse/YOMA-50)

![](gifSrc)
## Work Done
- added skills to state

    
## Screenshots

2021-08-07 21:21 UTC, cameronolivier requested changes

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.test.tsx
> +  describe('selector', () => {
add another test please - for with data.

2021-08-07 21:21 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const dropDownFromArray = (array: string[]) => {
This should be moved (along with the mapToDropDownArray above) out of the strings utils. 

as should  `sliceArrayByNumber` and `searchArrayOfObjByValue`

None of these are utils that work on strings. 

Both `mapToDropDownArray` and `dropDownFromArray` - for one they seem to be doing the same thing (in the end) - but neither of them makes much sense to what they're doing by how they are named.

But they should be moved to the `DropDown` component utils - as they are utils for preparing the data for the DropDown component.

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +export const fetchSkillsFlow: Middleware =
we should normalize the skills data - a key is the same as an ID - we might just need to slightly adjust the utils for normalizing so it pulls out the key instead of the ID.

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +      const skillEntities = selectSkillEntities(state) as []
we should know the shape of the skillsEntitites array, please type correctly.

2021-08-07 21:21 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const sliceArrayByNumber = (number: Number, array: any[]) => slice(0, number, array)
slicing is generally by number, so the naming is a bit obtuse.

I'd suggest something that describes slicing the array to a point.

so maybe `sliceTo` or `sliceAt`?

2021-08-07 21:21 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const searchArrayOfObjByValue = (query: string, array: any[]) =>
we are essentially filtering - so let's keep the same convention.

`filterByQuery` maybe?

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +  skillEntities: [],
I'd expect skillEntities to follow a similar shape to the other `<credential>Entities` flow in:
```ts
{ someKey: { key: 'someKey', value: 'someValue' }
```

if we're filtering it might be useful to have an additional  entitites and all mapping as:
```ts
skillsByName: { skillValue: {key: 'skill key', value: 'skill value'}}
allSkillNames: ['skillValue1', 'skillValue2', ....]
```
presuming this would be simpler to filter. Then searching would simply search across an array of strings - which will be faster than an array of objects
and results would be mapping over the filters and pulling in the data by the value. 

....finally, I think it might be worthwhile finding a third-party auto-complete component? Not sure if rolling our own would be worth the hassle?

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +  skillEntities: [],
Also this is the skills state key - so it feels redundant to repeat 'skills' in every prop name.
I think `filtered` and then `byValue` and `allValues` - and/or `byKey` and `allKeys`

To maintain the naming convention it might be useful to keep the naming convention here as `byId`- but that could cause confusion when looking at the data.

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.test.tsx
> +      const mockState = rootStateFixture({})
no need to mock state for this one.

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.test.tsx
> +      const state = store.getState()
you're just redoing the code that here - so you're not really testing anything (you're just testing that the same/similar code written in 2 places does the same thing.

Rather mock out what you expect your code to look like when you run this middleware - and assert against that. 

So mock decent state data with a decent query value - and then assert that you're dispatching with the expected values.

2021-08-07 21:21 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.test.tsx
> +      const skills = extractSkillsFromPayload(action)
again - you're simply repeating code you've already created -hence testing nothing.

Please mock out the expected data in and the expected data out - and make sure that your middleware is doing what you presume it is.

2021-08-11 11:23 UTC, sciphergfx commented on src/modules/Skills/Skills.reducer.tsx
> +  skillEntities: [],
there's a solution in place that handles this autocomplete part on the frontend. It's tied to the reducer, have you had a look?

2021-08-11 11:25 UTC, sciphergfx commented on src/modules/Skills/Skills.reducer.tsx
> +  skillEntities: [],
I think this may also apply to organisations in the long-run, we might need to standard approach on for that.

Do you reckon we stick to this
skillsByName: { skillValue: {key: 'skill key', value: 'skill value'}}
allSkillNames: ['skillValue1', 'skillValue2', ....]
skillEntities: { someKey: { key: 'someKey', value: 'someValue' }}

Please let me know what you think

2021-08-11 11:28 UTC, sciphergfx commented on src/modules/Skills/Skills.middleware.test.tsx
> +      const state = store.getState()
I'll attend to this, just need an idea on that state shape so I can replicate where needed

2021-08-12 20:47 UTC, cameronolivier requested changes
Some redux rules of thumb:
don’t store data in state that can be derived from the existing data.
use selectors to manipulate and derive the data you need for the component.

Then these are for use in our project:
don’t do data manipulation in reducers - do it in the middleware
stick to our convention for normalised state: {ids: string[], entities: {}} . you can swap ids out with keys - or another unique identifier depending on the data.

Don’t store data in state that can be derived from the existing data.
Store the data in skills state once. Have a selector that manipulates it if need be to what you require for usage in the component. In this case also don’t store filtered data in state - as we’re just slicing data. build this into a selector. 

Use selectors to manipulate and derive the data you need for the component.
Following on from above - use a selector to take the state data and derive it into how you might need it in the component - if that’s pulling out all values, or slicing for top 20, or whatever else you might need.

Don’t do data manipulation in reducers - do it in the middleware
Following the above 2 would solve this problem - but the way we’ve architected the app at the moment - things like normalising the data occurs in the middleware, not in the reducer.

2021-08-12 20:47 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const sliceAt = (number: Number, array: string[]) => slice(0, number, array)
this should not be in the strings utils. probably an array utils - or the ramda utils.

2021-08-12 20:47 UTC, cameronolivier commented on src/utils/strings.utils.ts
>  export const filterStringArray = (value: string, array: string[]) =>
also should be in the array utils - not in strings.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.types.tsx
> +export type NormalisedSkillsStatse = {
spelling mistake here

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(SkillsActions.fetchSkills())
can you update the tests for both of these.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.test.tsx
> +  describe('selector', () => {
Why did you remove the one without data? 
We need both initial state and with data tests for selectors.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.test.tsx
> +      const { skills } = result
please do this the other way around. We want to test that result equals {skills: mockFiltered}. not that the skills prop is correct-  but that the entire selector is as expected.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const filterSkillsByName = createAction<string>(`${name} filterSkillsByName`)
I don't think this is used anywhere? 
Or let me rephrase - you have middleware that catches it -but nowhere that's dispatching it.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +export const filterSkillsByNameFlow: Middleware =
as the action is never dispatched this will never run.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +export const filterSkillsByNameFlow: Middleware =
please remove this middleware - and the corresponding action

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +    if (fetchSkillsSuccess.match(action)) {
please see the UserChallenge module for an example on handling getting data, normalising in middleware and setting to state.

2021-08-12 20:47 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +  builder.addCase(setFilteredSkills, (state, action) => ({
should be handled by the selector

2021-08-13 10:36 UTC, sciphergfx commented on src/modules/Experience/Experience.selector.test.tsx
> +  describe('selector', () => {
As per comments from other PRs, I'm trying to stick with what the task says "add skills data to state", I'll add selectors when we get to relevant stories

2021-08-16 20:34 UTC, cameronolivier requested changes
small change. otherwise looking good! :)

2021-08-16 20:34 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +  objFromListWith(ifElse(has('key'), prop('key'), prop('id'))),
### Issue: should avoid longer, nested functions

### Suggestion:
I think it's a simpler, and more straightforward way to simply pass the prop, with a default value:
```ts
export const normalise = (data, identifier = 'id') => pipe(
  objFromListWith(prop(identifier)),
```
and use it like so:
```ts
normalise(data)
// OR:
normalise(data, 'key')
```

2021-08-18 21:00 UTC, cameronolivier requested changes

2021-08-18 21:00 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +export const normalise = (data: any, identifier = 'id') =>
nitpick: data type should be:
```ts
data: Record<string, any>[]
```

2021-08-18 21:00 UTC, cameronolivier commented on src/types/general.types.ts
> +export type StdFn<T = any, R = void> = (args: T, identifier?: string) => R
issue: we shouldn't adjust this - as it's meant to be a generic function type, so setting the second argument means it can't be used elsewhere.

The original is typed so that it can only take 1 argument, which limits its utility.

suggestion: 
I can think of 3 decent options - feel free to use or not use:
**Option 1:** Manually type it in the `skills.middleware`: 
```ts
(payload: Skill[], identifier: string) => NormalisedSkills
```

**Option 2:** Create a new generic type that takes 2 arguments:
```ts
export type StdFn2Args<Arg1 = any, Arg2 = any, Return = void> = (arg1: Arg1, arg2: Arg2) => Return
```
usage in the Skills middleware:
```ts
StdFn2Args<Skill[], string, NormalisedSkills>
```
This will work, but obviously only works with functions with 2 arguments. 

**Option 3:** create a generic type that takes `n` arguments:
```ts
export type StdFnWithArgs<Args = any, Return = void> = (...args: Args[]) => Return
```
usage in the Skills middleware:
```ts
StdFnWithArgs<Skill[] | string, NormalisedSkills>
```
_Issue is we aren't STRICTLY typing the inputs here, as in you could switch the action.payload and the key around in the call and typescript wouldn't throw an error, so options 1  or 2 would be more precise_ 
ie this wouldn't throw a typescript error, but it would cause the function to error:
```ts
 normalise('key', action.payload)
```

2021-08-18 21:21 UTC, sciphergfx commented on src/types/general.types.ts
> +export type StdFn<T = any, R = void> = (args: T, identifier?: string) => R
So since the function is instantiated with "id", that will always be a constant hence identifier being optional. Tried option 2 before taking that position. Happy to refactor otherwise, Which option do you advice I effect just so we're are on the same page? @cameronolivier

2021-08-18 21:25 UTC, cameronolivier requested changes

2021-08-18 21:25 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(SkillsActions.clearSkills())
issue: Skills should not be cleared (arguably ever).

2021-08-18 21:33 UTC, cameronolivier commented on src/types/general.types.ts
> +export type StdFn<T = any, R = void> = (args: T, identifier?: string) => R
@sciphergfx 

so the primary thing is we shouldn't be changing a generic type for a specific use-case.

The typing for the specific usecase in skills is that it takes 2 args, even though the second is optional.

A 4th option might be to create an actual type for the `normalise` function, that you then simply use everywhere you want to import `normalise`. 

```ts
export type Normalise<Data, NormalisedData> = (data: Data[], identifier?: string) => NormalisedData
```
usage in the Skills middleware:
```ts
Normalise<Skill, NormalisedSkills>
```

If I were doing it, I'd probably go with the above option. Otherwise, I'd go with 2, or 1 (2 is slightly better than 1 imo, because it has more utility down the line)

2021-08-18 21:50 UTC, cameronolivier approved these changes
Just a comment to move that new Normalise type -but can do in Organisations PR.

2021-08-18 21:50 UTC, cameronolivier commented on src/types/general.types.ts
> +export type Normalise<Data, NormalisedData> = (data: Data[], identifier?: string) => NormalisedData
this is great - but I think it should be in a different file. Happy for you to do this in the next PR so we can get this in. 

I'd suggest creating a `redux.types.ts` file in this folder and adding it there.

2021-08-18 21:53 UTC, sciphergfx commented on src/types/general.types.ts
> +export type Normalise<Data, NormalisedData> = (data: Data[], identifier?: string) => NormalisedData
We can merge, waiting to effect some changes on organisations PR @cameronolivier

2021-08-18 21:53 UTC, merged