YOMA-451 - refactor(Experience): experience should correctly show all the user s entries
didx-xyz/yoma-mobile pull request #107
Opened 2021-08-07 17:33 UTC by sciphergfx

## Scope [YOMA-451](https://yomaworld.atlassian.net/browse/YOMA-451)

![](gifSrc)
## Work Done
- integrated jobs state to experience container
- added utils and selectors to experience
- added tests where necessary

2021-08-08 11:32 UTC, cameronolivier requested changes
This feature is meant to handle displaying data - so should arguably have the middleware that pulls the data out of state and saves into middleware. 

It should not have anything that handles adding/saving new experience. 

I'd suggest refactoring between this and 452 so that this lays the foundation for getting the data into state and 452 handles saving editing the data.

It will make this a bit bigger (which is perfectly fine - it's only 8 files) and will reduce 452 in size which is great as it's still 50 files large.

Also if we do it that way, this should be able to go in first and separate to 452. 

And 452 can then only be concerned with saving or editing a specific user experience instead of trying to handle all of these things in one massive chunk of work.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +import { selectJobEntities } from 'modules/Job/Job.selector'
should we not be getting the jobs from the user credentials - not from the Job modules-  which would be all the jobs.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +const mapDispatchToProps = (dispatch: Dispatch) => {
this story just cares about _displaying_ the experience data - not about any of the editing. You've added a bunch of code aimed at handling the editing part - which should be extracted into `452` - where it's meant to be handled.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +import { selectJobEntities } from 'modules/Job/Job.selector'
if this is the credentials, then it should be inside the User module as discussed.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  onJobCreate: (job: JobRequestPayload) => void
as mentioned above we should only be handling data required for displaying the user's experiences in this story. I presume that would simply be jobs.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  jobs: []
please type this correctly.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +    setJobsList(Object.values(jobs))
please set the data you need in the selector - that's where we should be preparing the data for a component - not in the component itself.

Also - we should have these normalised.

2021-08-08 11:32 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +              keyExtractor={(item: any, index: number) => index.toString()}
this shouldn't be necessary, I don't think - but also - don't all credentials have ids? so our list of experience should have an id attached - if it's not pulling it in automatically, then we should be getting it from there.

2021-08-23 18:14 UTC, cameronolivier requested changes

2021-08-23 18:14 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.ts
> +export type UserJobsList = {
suggestion: I think this should maybe be `UserJobItem`? it's not a list - it's an item (that may or may not be in a list) 

IF we need to differentiate between this and the widget or other UserJobItems, then maybe UserJobScreenItem or UserJobWidgetItem for the widget data.

2021-08-24 20:55 UTC, cameronolivier requested changes

2021-08-24 20:55 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.constants.ts
> +export const MOCKED_JOBS = [
issue: you can remove this - it's not used at all in the project.

2021-08-24 20:55 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
>    const renderItem = (item: any) => {
suggestion: I think we should move this outside the component. Happy to keep it in the same file (although it might be best to extract into its own component).

2021-08-24 20:55 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  const [userJobsItems, setUserJobItems] = useState<UserJobsTypes.UserJobItem[]>([])
issue: this serves no purpose.
suggestion - remove this and simply inject `userJobs` directly into the flatlist data.

2021-08-24 20:55 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +export const selectUserJobItem = createSelector(
nitpick - I was going to say that this should be plural (`selectUserJobItems`) - but maybe it's best to simply make this the default selector and then no need to name it at all. 

Essentially you're wanting to select the user jobs formatted for the user job item. but that's a little verbose - and as we're using the default selector I don't see any reason not to simply export this all as a single default selector. 

just add `objOf({userJobs})` to the end of the pipe on line 10.

2021-08-24 20:57 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +export const selectUserJobItem = createSelector(
suggestion: Forgot to add -please remember to bump version and release notes.

2021-08-24 21:57 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.selector.tsx
> +export const selectUserJobItem = createSelector(
A bit puzzled with regards the use of objOf({userJobs}), props needed on the UI is {'job', 'startDate', 'endDate'}?

2021-08-24 21:59 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.tsx
>    const renderItem = (item: any) => {
Our component has less than 150 lines, I doubt it would be re-used, shall I extract nonetheless?

2021-08-25 19:48 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
>    const renderItem = (item: any) => {
you can keep it there for now.

2021-08-25 19:51 UTC, cameronolivier approved these changes

2021-08-25 21:21 UTC, merged