YOMA-501 - refactor: added jobs data to state
didx-xyz/yoma-mobile pull request #109
Opened 2021-08-09 09:30 UTC by sciphergfx

…objects

## Scope [YOMA-501](https://yomaworld.atlassian.net/browse/YOMA-501)

![](gifSrc)
## Work Done
- added jobs data to state
- refined normalise util function to accept object

## Steps to Test

    
## Screenshots

2021-08-09 17:08 UTC, cameronolivier requested changes
Job or Jobs should be inside `User` module if it's a user credential, as discussed.

If it's just a list of data (jobs/organisations, etc) _NOT_ tied to the user then it should have a root-level module.

2021-08-09 17:08 UTC, cameronolivier commented on src/api/api.utils.ts
> +export const appendIdToEndpointInConfig = (config: Partial<ApiMeta>) => (id: string) =>
needs tests added

2021-08-09 17:08 UTC, cameronolivier commented on src/api/api.utils.ts
> +export const extractPayloadData = path(['payload', 'data', 'data'])
need tests added

2021-08-09 17:08 UTC, cameronolivier commented on src/modules/Error/Error.utils.ts
> +export const extractErrorMessageFromPayload = path(['payload', 'data', 'meta', 'message'])
I'd think we might need 2 utils - 1 to extract the meta (although we might have that already?) and then a second to access the message in meta? or what do you think?

2021-08-09 17:08 UTC, cameronolivier commented on src/modules/Experience/Experience.types.ts
> +  values: FormikValues
FormikValues seems to be very generic. surely we need more typing here? I'm presuming values for here would be different to values for another form?

2021-08-09 17:08 UTC, cameronolivier commented on src/modules/Job/Job.middleware.test.tsx
> +describe('modules/Jobs/Jobs.middleware', () => {
should be singular

2021-08-09 17:08 UTC, cameronolivier commented on src/modules/Job/Job.middleware.tsx
> +import { extractPayloadData } from 'api/api.utils'
so it seems you're doing both global jobs and specific user experience calls within the one module - I think it should be separated out, as discussed, into 
- `Jobs` - which handles all jobs (via `​/api​/v1​/jobs...` api calls) and 
- `User/Jobs` or the more I think of it `User/Experience` which handles all of the User's experience/jobs and is managed by `​/api​/v1​/users​/{userId}​/credentials...` api calls.

2021-08-09 17:08 UTC, cameronolivier commented on src/modules/Job/Job.middleware.tsx
> +import { extractPayloadData } from 'api/api.utils'
This comment applies for this entire Jobs module that you created as well as any other place where credentials assigned to a user are managed separately to all possible entities for a given category (Skills, Challenges, etc)

2021-08-10 08:29 UTC, sciphergfx commented on src/api/api.utils.ts
> +export const appendIdToEndpointInConfig = (config: Partial<ApiMeta>) => (id: string) =>
This is in YOMA-452, remember it was extracted, but i'll add

2021-08-10 08:29 UTC, sciphergfx commented on src/api/api.utils.ts
> +export const extractPayloadData = path(['payload', 'data', 'data'])
same as above

2021-08-10 08:29 UTC, sciphergfx commented on src/modules/Error/Error.utils.ts
> +export const extractErrorMessageFromPayload = path(['payload', 'data', 'meta', 'message'])
noted

2021-08-10 08:30 UTC, sciphergfx commented on src/modules/Experience/Experience.types.ts
> +  values: FormikValues
I agree

2021-08-10 08:33 UTC, sciphergfx commented on src/modules/Job/Job.middleware.tsx
> +import { extractPayloadData } from 'api/api.utils'
I understand you. So skills is not a user credential per-say, but compliments them. The API handles it differently if I'm not mistaken?

2021-08-10 17:18 UTC, sciphergfx commented
re-open

2021-08-10 20:24 UTC, cameronolivier requested changes

2021-08-10 20:24 UTC, cameronolivier commented on src/api/api.utils.test.ts
> +  describe('extractPayloadData', () => {
this should now be in develop :) 

I added it to the redux utils because we're extracting from an action.... but maybe it should actually be in api utils because it's not general extraction - it's typical to api response data....

So if you feel like moving that - go for it - but otherwise use it from `src/utils/redux.utils.ts`

2021-08-10 20:24 UTC, cameronolivier commented on src/api/api.utils.ts
> +export const extractPayloadData = path(['payload', 'data', 'data'])
as mentioned in the tests -this is now in the project in `src/utils/redux.utils.ts` - I think that should be moved. Either here - or to `src/utils/api.utils.ts`

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +import * as JobsActions from '../UserJobs/UserJobs.reducer'
this should be `UserJobsActions`.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/Experience/Experience.types.ts
> +  job: UserJobsOrganisationPayload
If this is just an Organisation, then let's call it that. If it's a JobsOrganisation, then let's call it that - I think ONLY add 'Payload' if it's specifically a payload shape - and we're using a different shape in the app. When it's actual data that we're using around the app, adding 'Payload' is a bit redundant -and unnecessarily verbose.

So - as I have a `Challenge` - which is the `challenge: {...}` part of the data and UserChallenge which is the `Challenge` + `UserCredentialMeta` - could you not follow a similar naming pattern? 

And further why would the Experience > job be a UserJobsOrgansationPayload? The naming doesn't seem to map. Surely it should be something like `job: UserJob`?

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const fetchUserCredentialsFailureFlow =
We do need this - thank you! that's a good catch :) 

Could we move this next to the fetchUserCredentialsFlow middleware (Around line 80) - so that they're grouped-  otherwise it's hard to see if we're missing something or the flow of things.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const fetchUserCredentialsSuccessFlow: Middleware =
please follow my flow - and have middleware to extract the jobs in your UserJobs module. 

The User module shouldn't care about what other module needs what data in a success payload it's firing off. 

Right now the User module doesn't actually need to do any handling of the data (except if you simply want to extract the payload data and pass that on - that would be useful - but then it should dispatch a new action, something like `userCredentials` with the extracted userCredentials from the payload.

So the body of this middleware would simply be something like:
```ts
if (fetchUserCredentialsSuccess.match(action)) {
    const userCredentialData = extractPayloadData(action)
    dispatch(userCredentials(userCredentialData))
  }
```

And then we'd need to update my UserChallenges module to listen for that action instead.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const jobs = extractCredentialsByType(UserCredentialTypes.Job)(userCredentialPayload)
so this needs to move to the UserJobs middleware.

See my Challenges example.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      dispatch(setUserJobsEntities(normalise(jobs)))
Please don't call a function on the data inside an action dispatch. Call it separately - and preferably in its own middleware.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +  createUserJobs,
I think this middleware is doing too much for a 'add [User]Jobs data to state' task. 

See my Challenges - it's a good overview of what we need to be doing in the credentials. 

If it grows as we add editing & saving (in 452) then obviously that's great - but it shouldn't be in this PR

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +  createUserJobs,
None of the current middleware is required for this story. And the middleware that should be here isn't. Please refactor.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.tsx
> +import { createAction, createReducer } from '@reduxjs/toolkit'
there's also too much going on here for simply adding UserJobs data to state. 

We simply need actions that handle whatever you need to do that. Adn state should reflect that too - I'm not sure what tmpFormValues are - but they won't be needed here. 

I think all you need right now is 
```ts
{
 ids: [],
 entities: {},
}
```

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.tsx
> +import { createAction, createReducer } from '@reduxjs/toolkit'
but - do what you need specifically to Add USER Jobs data to state.

If it's _all_ jobs - that needs to move to the Jobs module. 
If it's anything to do with managing the form or adding or editing user experience-  that needs to be in 452 - or other stories.

All this story/task should care about is pulling the UserJobs data out of the `fetchUserCredentialsSuccess` action payload, normalising it correctly and saving it to state. Nothing more, nothing less.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +import { createSelector } from '@reduxjs/toolkit'
we don't need a selector yet.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.test.fixtures.ts
> +export const jobCredentialsStateData = {
this shouldn't be a fixture - it has little bearing on real data - it's really just a mock - which can be inline (And should be inline) - Tests are one place where you don't need to be DRY - it's better to keep data that you're testing as close to the test code as possible - so only abstract if it's really bulky and/or fixture data (as in mocked actual response data) - (as above)

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +import { UserCredentialMeta } from 'modules/User/User.types'
this doesn't exist on `User/User.types` according to my IDE (I double-checked and I can't find it either)

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsPayload {
remove 'Payload' if it's being used as a UserJob in the app - Payload adds nothing here (and can cause confusion)

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsOrganisationPayload extends UserJobsPayload {
I think this can/should be named better.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsCredentialsTmpFormValues {
what is this? also I don't think we need this yet.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsResponsePayload {
so this seems to be correctly named as a Payload.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsResponsePayload {
That said, we could probably remove 'Payload' as it actually looks like a Response. We don't need to postfix Payload to everything (unless it's ONLY a Payload data shape AND removing the Payload would clash with a different type)

Basically - never prefix Payload unless it makes a LOT of sense and there's no other option.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +  job: UserJobsOrganisationPayload
this should really just be `Job` - unless there's another `Job` interface that is considerably different.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +  tmpFormValues?: any
please adjust this to reflect what the state should be on fetching Jobs data - which should just be normalised jobs 
```ts 
{
id: string[],
entities: Record<string, UserJobs[]> 
}
```
presuming `UserJobs` is the type for the UserJob (I think you called it `UserJobsCredentials`, but I think `UserJob` is probably sufficient, and consistent with the Challenge naming convention. At any rate keep the naming convention singular if it's typing a single entity. (so `UserJob` not `UserJobs`).

2021-08-10 20:24 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +  ifElse(is(Array), identity, of),
we should only be normalising arrays of objects - that's what normalising does - so there's no need to be catering for non-arrays here.

2021-08-10 20:24 UTC, cameronolivier commented on src/redux/middleware.ts
> +  UserJobsMiddleware.createUserJobsFlow,
I expect this will update once you've refactored the rest.

2021-08-10 20:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +
It looks like none of these are required for this work

2021-08-11 12:03 UTC, sciphergfx commented on src/modules/User/User.middleware.ts
> +export const fetchUserCredentialsSuccessFlow: Middleware =
I'll have a look at your implementation. As discussed, i thought this was meant to pull the respective credentials in to their states

2021-08-11 12:04 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +  createUserJobs,
I extracted most of these changes to make the PR smaller

2021-08-11 12:07 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsResponsePayload {
we have payload suffix in other parts of the code, it was a reference but noted

2021-08-11 12:08 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.types.tsx
> +  job: UserJobsOrganisationPayload
It also serves as a type for an API response payload

2021-08-11 12:26 UTC, sciphergfx commented on src/utils/redux.utils.ts
> +  ifElse(is(Array), identity, of),
As per the API documentation, I added this to support credential responses that are in object shape after a successful create/update operation

2021-08-11 12:26 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.types.tsx
> +import { UserCredentialMeta } from 'modules/User/User.types'
I'll re-add this. some how landed in another PR

2021-08-11 22:59 UTC, cameronolivier requested changes
Changes to date. Please complete these current changes before I'll review again.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/Experience/Experience.types.ts
> +  job: UserJobsOrganisation
this still doesn't really make sense - is this for a UserJob or a UserJobOrganisation - and if the latter - why is the property called `job`?

2021-08-11 22:59 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +  ifElse(is(Array), identity, of),
Ok.

2021-08-11 22:59 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +  ifElse(is(Array), identity, of),
Please update the tests to cover this use case.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.tsx
> +export interface UserJobsResponsePayload {
I hear you. they might need to be refactored.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const fetchUserCredentialsSuccessFlow: Middleware =
Maybe there was a misunderstanding - but I definitely said many times that each of the modules handle pulling the data they need out of the `fetchUserCredentialsSuccess` action payload.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +  createUserJobs,
I don't think we're on the same page. 

We're trying to achieve 2 things. 1 - we need to break the larger chunks of work into smaller chunks of work. but 2. those chunks still need to make sense with what we're trying to achieve. As this was said to be a 'add jobs data to state' task - it doesn't make sense to do all crud tasks here. If we are doing all CRUD tasks in this PR, then I'll review it as such - but I think it makes more sense to do each of the pieces of functionality as we need them. 

So in preparation for the displaying data (451), we need to store data.
In doing the 452 -handling edit/add/delete, we need to be able to update or add or delete via the api.
I suppose it's how we want to break the work up - but once again - if the story says you're doign something try stick to that thing.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +  extractUserJobsCredentialId,
I don't think we need to user 'credentials' in our naming here.

I think `Jobs` for unnattached jobs and `UserJobs` for user experience is 100% - and the pattern we should use for the rest of the credentials work.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +export const createUserJobsSuccessFlow: Middleware =
this should be singular, right? we're creating a single job.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +          mergeRight(ApiUserJobsConstants.JOBS_CREATE_CONFIG, {
this is not ApiUserJobsConstants but simply ApiJobsConstants.

Please move all Jobs creation to the Jobs module as discussed.
All User Job Credentials CRUDS should be called UserJob(s) and be in the UserJobs module. As discussed.

2021-08-11 22:59 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.tsx
> +          mergeRight(ApiUserJobsConstants.JOBS_CREATE_CONFIG, {
And again we're moving away from what was put in the job name. This is why I keep pushing to do specifically what we set our stories to - because when we do too much - each little change has knock-on effects. You know you can't properly create a new job experience credential without first creating a new job, and creating/tying to an organisation - and we'll be right back where we started with 452 - in being too large. It's frustrating for me that you don't get this and that there is constant push back on these things - which actually make us faster and make sure we're not diverging too far from what we're trying to achieve.

2021-08-14 15:03 UTC, cameronolivier requested changes
Can you bump the version number so long - we can then update if something else goes in first - but at least we won't miss it.

2021-08-14 15:03 UTC, cameronolivier commented on src/redux/reducers.ts
> +  job,
issue: we need a consistent naming convention around plural/singular.
suggestion: [blocking] this needs to be 'jobs'

2021-08-14 15:03 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.test.ts
> +describe('src/modules/User/Jobs/Jobs.redux', () => {
nitpick: [optional] Jobs.redux should be Jobs.reducer

2021-08-14 15:03 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const fetchUserCredentialsFailureFlow =
nitpick: please move this closer to `fetchUserCredentialsFlow`

2021-08-14 17:25 UTC, cameronolivier requested changes

2021-08-14 17:25 UTC, cameronolivier commented on release-notes.txt
>  - docs upgrade, no new features added.
nitpick: 
Please add the latest release notes under **Latest**
and move the current latest to top of the **Recent**

```text
Ver 0.0.1
Latest:
- added jobs and user jobs to state

Recent:
- adding User Challenges credentials to state
- adding helper utils for handling MyCV data
- docs upgrade, no new features added.
- Adjusted the widgets on MyCv to be able to take different types of content (previously they could only take text)
```

2021-08-14 17:55 UTC, cameronolivier approved these changes

2021-08-14 17:56 UTC, merged