YOMA-533 - refactor(UserJobs): UserJobs (Experience) - Add user job credential to state
didx-xyz/yoma-mobile pull request #115
Opened 2021-08-19 16:53 UTC by sciphergfx

## Scope [YOMA-533](https://yomaworld.atlassian.net/browse/YOMA-533)

![](gifSrc)
## Work Done
- Redux setup from userJob creation
- Modified UserJob State to hold temporary values for userJob credential creation
- Added util to update state entities on when User<credentialType> is created
- Added tests where necessary

2021-08-19 19:44 UTC, cameronolivier requested changes

2021-08-19 19:44 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +export const extractNormalisedEntitiesFromState = pick(['ids', 'entities'])
nitpick/suggestion: this is really just a selector - anything from state should use 'select' - so this is sort of a selector utility - so I'd suggest naming it `selectNormalised`.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +export const selectUserJobsFormValues = createSelector(selectUserJobs, path(['formValues']))
suggestion: `prop` would be better than `path` in this situation.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const createUserJobs = createAction<any>(`${name} createUserJobs`)
suggestion/nitpick: I presume this should be singular? `createUserJob`
nitpick: And could you type the payload.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.test.ts
> +    it('should correctly add the usrJobs data', () => {
nitpick: spelling mistake : should be userJobs or user jobs

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/User/User.types.ts
> +export interface UserCredentialItemPayload {
question: is this the shape of the data returned when adding a credential?

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/User/User.types.ts
>  export type UserCredentials = UserChallenge[]
issue: please add the UserJobs[] to this.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const extractCredentialPayload =
issue: please add tests

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.ts
> +import { ApiMetaResponse } from 'modules/Auth/Auth.types'
suggestion - if this is a shared type now, we should refactor this and move it to a shared folder - ie if it's not Auth-specific. 

maybe in api.types in the src/types folder? or if you can think of a better place for that.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.types.ts
> +  formValues?: UserJobsFormValues | null
nitpick: this shouldn't be optional as it's always there - it's just either `UserJobsFormValues | null` so can drop the `?`

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +  merge({
issue: `merge` is deprecated - rather use `mergeRight`  or `mergeDeepRight` if you want recursive merge.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +export const extractJobId = path(['payload', 'id'])
suggestions: it seems this is by its nature a generic function (it'll extract any id from a given payload. Might be useful to add it as a shared util in the `src/utils` folder - probably in api utils? or if you have a better idea as simply `extractId`

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +export const extractUserCredentialFormValues = (
nitpick: as this is generic, please move it to the User.utils file.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.test.tsx
> +    it('should return the jobs credentials form values from state', () => {
question/nitpick: is this correct? aren't you getting the values from an action payload, not from state?

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +export const extractUserJobsPayload = (action: any): StdFn<any, UserCredentialItemPayload> =>
suggestion: rename this to something that better describes what this is doing.

This function seems to be merging the create job payload with form data from state. 
Alternatively, it looks like it might be preparing the "create job credential" payload. 

So naming it so that it reflects what it's doing means it's easier to understand the code without having to interrogate the actual function. 

currently, our 'extract' utils are pulling data out of a payload. If we're doing more we should rename to reflect that.

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.test.tsx
> +    it('should return the userJobs form values from state', () => {
nitpick: I don't think this is what this is doing. because that's what the selector is doing. This is merging form values with payload data

2021-08-19 19:44 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +export const extractUpdatedNormalisedState = (
issue/nitpick:This isn't extracting anything - it shouldn't be prefixed with extract. it looks like a reducer utility, but it isn't extracting anything, so please rename. 

I'd suggest something like `updateNormalisedState`

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +    if (updateNormalisedUserJobsState.match(action)) {
issue: what you're doing here should be handled in the reducer. 

suggestion: I'd suggest you do the following:

have an `updateUserJobs` action.
simply dispatch the payload of `normalisedJobs`

then in the reducer, use a version of your `extractUpdatedNormalisedState` (or as suggested `updateNormalisedState`) util.
```ts
builder.addCase(updateUserJobs, (state, action) => updateNormalisedState(state, action.payload))
```
and that's it. :)

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +      dispatch(updateNormalisedUserJobsState(normalisedJobs))
suggestion: Here's a suggested middleware flow that will be a bit cleaner: 

`createUserJobSuccessFlow`: (note this should be singular `Job`
do: 
- extractDataFromPayload
- normalise the data.
- dispatch: updateUserJobs(normalisedJobs)
- Navigation.navigate(HomeNavigationRoutes.Experience)
- notification('success', 'Details saved!')

then catch `updateUserJobs` in the reducer and simply merge state there (I've pasted the relevant bits from my comment below in `updateNormalisedUserJobsStateFlow`):

In the reducer, use a version of your `extractUpdatedNormalisedState` (or as suggested `updateNormalisedState`) util.
```ts
builder.addCase(updateUserJobs, (state, action) => updateNormalisedState(state, action.payload))
```

2021-08-19 19:44 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +export const selectUserJobsFormValues = createSelector(selectUserJobs, path(['formValues']))
suggestion: I think you could shorten this to simply `selectFormValues` - you can see other selectors- you don't really need to name explicitly. If you do use this selector in a different module our pattern is to import the module as `UserJobsSelectors` - so usage would be `UserJobsSelectors.selectFormValues` which would be fine.

2021-08-20 06:39 UTC, sciphergfx commented on src/modules/User/User.types.ts
> +export interface UserCredentialItemPayload {
So this is the request payload when adding a credential. Response is UserChallenge[]

2021-08-20 06:54 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.utils.tsx
> +export const extractUserJobsPayload = (action: any): StdFn<any, UserCredentialItemPayload> =>
Do you have name suggestions here?

2021-08-20 22:42 UTC, cameronolivier requested changes

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const updateNormalisedUserJobs = createAction<NormalisedUserJobs>(`${name} updateNormalisedUserJobs`)
suggestion/nitpick: This shouldn't specify `normalised` - because _state_ is normalised - so there's no need to make the distinction here. You're simply updating the userJobs in state so `updateUserJobs` is perfectly fine. Just as you have `setUserJobs` (which is also normalised - but there's no need to specify it there either).

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const createUserJobsSuccess = createAction<UserJobsResponse>(`${name} createUserJobsSuccess`)
nitpick: (non-blocking) considering I'm already nitpicking - success/failure of `createUserJob` should also be singular.

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +export const createUserJobsFlow: Middleware =
nitpick should also be singular.

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +import { selectId } from 'modules/User/User.selector'
issue: this needs to be `import * as UserSelectors from 'modules/User/User.selector'`, because it gives context to what `selectId` is doing. Right now it's not obvious which id selectId is retrieving from state.

by importing as `* as UserSelectors` you can use it as: `UserSelectors.selectId` which now makes more sense. 

We should be importing all external module imports for these types of contexts in this manner.

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +export const createUserJobsSuccessFlow =
nitpick: (non-blocking) should be singular

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +export const createUserJobsFailureFlow =
nitpick: (non-blocking): should be singular

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +import { selectFormValues } from './UserJobs.selector'
comment: it's fine to import within the module like this - just external modules should be `* as ...`

2021-08-20 22:42 UTC, cameronolivier commented on src/modules/Jobs/Jobs.middleware.tsx
> +import { createUserJob } from 'modules/UserJobs/UserJobs.reducer'
issue: this should be `import * as UserJobsActions` and used as `UserJobsActions.createUserJob`

2021-08-21 00:02 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const updateNormalisedUserJobs = createAction<NormalisedUserJobs>(`${name} updateNormalisedUserJobs`)
this is named "updateNormalisedUserJobs" as "updateUserJobs" edit actions for API is coming in.

2021-08-22 15:24 UTC, cameronolivier approved these changes

2021-08-22 15:24 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const updateNormalisedUserJobs = createAction<NormalisedUserJobs>(`${name} updateNormalisedUserJobs`)
Then we need a better naming convention.

Adding `normalised` doesn't add any value here or indicate whether it's updating state or the api. 

Using `select`/`set`/`update` for state naming makes sense.

I think we should adjust our naming convention for setting it to `adjust`.
`fetch`/`create`/`adjust` for api methods. 

What you think?

2021-08-22 15:38 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.reducer.ts
> +export const updateNormalisedUserJobs = createAction<NormalisedUserJobs>(`${name} updateNormalisedUserJobs`)
Outdated comment this seems, changes was already made here

2021-08-22 17:20 UTC, merged