YOMA-544 - feat(Skills): add filtered skills to state
didx-xyz/yoma-mobile pull request #118
Opened 2021-08-22 14:39 UTC by sciphergfx

## Scope [YOMA-544](https://yomaworld.atlassian.net/browse/YOMA-544)

![](gifSrc)
## Work Done
- add filtered skills to state
- default number of skills to form component 20

2021-08-23 20:32 UTC, cameronolivier requested changes

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.selector.test.tsx
> +              idA: 'Skill A',
could you make these values different to the std values below - because in this test you could be pulling in the entities data and the test wouldn't warn you.

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.selector.tsx
> +export const selectEntities = createSelector(selectSkills, path(['entities']))
suggestion: prop is better than path here - it's simpler and to the point

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.types.tsx
> +  filtered?: []
issue: this should be a typed array.

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.test.tsx
> +      const mockEntities = zipObj(keys(repeat(0, 30)), repeat({ key: 'key', value: 'skill' }, 30))
suggestion: extract something like this into a little test helper util with a name that says what it does - which makes it easier to get what's happening in the test itself.

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const setFilterSearchTerm = createAction<any>(`${name} setFilterSearchTerm`)
nitpick - please type this - it should be a string I'd think

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +export const extractFilteredSkillsByValue = curry(({ searchTerm, entities }: SkillsState) => {
suggestion/nitpick: this should be named `selectFiltered....` not `extractFiltered...` because you're selecting here. - or probably better:
`filterSkillsByValue` or `filterSkillsByTerm` <- I think this is best because you're filtering the skills by the search term.

2021-08-23 20:32 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +  return isEmpty(searchTerm) ? slice(0, 20, filtered) : filtered
Issue: we should exit before doing expensive work if we don't need to (ie do the searchTerm length/empty check first.

Then continue with the filtering only if it's not empty (ideally less than 3 length, correct?) 
(also, I don't think you need to curry this - unless you want to be able to call it as a curried function or as a single call.

Suggestion:
```ts
export const extractFilteredSkillsByValue = curry(({ searchTerm, entities, minTermLength = 3 }: SkillsState) => {

 if (searchTerm.length < minTermLength) {
    return slice(0, 20, entities)
 }

return pipe(
    values,
    filter((obj: any) => obj.value.indexOf(searchTerm) === 0),
  )(entities)

}

```

2021-08-24 06:30 UTC, sciphergfx commented on src/modules/Skills/Skills.utils.tsx
> +  return isEmpty(searchTerm) ? slice(0, 20, filtered) : filtered
Ah.. I missed the minTermLength for this logic. With regards the function, I'm not sure we should be setting 'minTermLength' in redux state as suggested, if you noticed, {searchTerm, entities} were destructured.

2021-08-24 20:23 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +  return isEmpty(searchTerm) ? slice(0, 20, filtered) : filtered
on the `minTermLength` I hear you - I think then store it as a constant - I suppose this isn't a function that would be used anywhere but in the set context - so that's fine.

Alternatively we can use `isEmpty` - it's easy enough to swap out (or simply set `minTermLength` to 0 and the check to `if (searchTerm.length <= minTermLength) {`.

Right. the code will be the same (So either extract it into a util that does that or simply replicate it) - but running that on 20 entities vs 2500++ (or however) will be vastly faster?.

Way to do it - is get id's in here too. Then simply slice first 20 ids, and map over that returning the value. something like this (ignore the naming): 
```ts
top20.map( id => entitites[id].value)
```

2021-08-24 20:29 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +  return isEmpty(searchTerm) ? slice(0, 20, filtered) : filtered
suggestion: I wonder if the returned couldn't be refined a bit too. 

Ramda's `filter` function works directly on objects so you shouldn't need to run values on it first. If you want to return the values, I'd suggest swapping the 2 lines around:
```ts
return pipe(
    filter((obj: any) => obj.value.indexOf(searchTerm) === 0),
    values,
  )(entities)
```

nitpick: please type the obj.

2021-08-24 20:34 UTC, cameronolivier requested changes
Left some further comments to the `selectFilterSkillsByTerm` util as comments (not part of this review) - so please make sure not to miss that :)

2021-08-24 20:34 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +export const selectFilterSkillsByTerm = curry(({ searchTerm = '', entities }: SkillsState, minTermLength = 3) => {
suggestion: I don't need to curry this as it's a single argument (it just receives the skills state) so there's nothing to curry. (currying simply allows you to send `n` arguments to a function as single arguments across `n` functions).

_PS. Sorry I missed the destructuring in my previous comment - meant it as a separate argument._

2021-08-24 21:25 UTC, sciphergfx commented on src/modules/Skills/Skills.utils.tsx
> +export const selectFilterSkillsByTerm = curry(({ searchTerm = '', entities }: SkillsState, minTermLength = 3) => {
just confirming no change to effect here?

2021-08-24 21:31 UTC, sciphergfx commented on src/modules/Skills/Skills.utils.tsx
> +  return isEmpty(searchTerm) ? slice(0, 20, filtered) : filtered
I'm a bit puzzled with the change required here. Do you have a code suggestion for this block perhaps? @cameronolivier

2021-08-25 15:38 UTC, cameronolivier submitted a review, later dismissed
Approved with comment.

2021-08-25 15:38 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +export const selectFilterSkillsByTerm = curry(({ searchTerm = '', entities, ids }: SkillsState) => {
nitpick: happy for you to refactor this in 452 or 451, but this doesn't need to be curry'ed

2021-08-25 20:16 UTC, cameronolivier requested changes
Hey. looks like you still need to bump the version

2021-08-25 20:16 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.test.tsx
> +    it('should extract skill name from entities', () => {
suggestion: (non-blocking) I'd suggest adding a test to better show how this works - as in make the search term a partial match - but happy otherwise. Can do this in another PR if you wish.

2021-08-25 21:01 UTC, sciphergfx commented on src/modules/Skills/Skills.utils.test.tsx
> +    it('should extract skill name from entities', () => {
need to tied all up on 452, I can effect this on the PR. I just need both PRs in if possible

2021-08-25 21:06 UTC, cameronolivier approved these changes

2021-08-25 21:20 UTC, merged