YOMA-520 - feat(UserSkills): store user skills credentials in state
didx-xyz/yoma-mobile pull request #121
Opened 2021-08-27 11:01 UTC by sciphergfx

## Scope [YOMA-520](https://yomaworld.atlassian.net/browse/YOMA-520)

![](https://giphy.com/embed/xHurQ6PtIJRG0WgLBk)
## Work Done
- redux setup for userSkills

2021-08-30 21:05 UTC, cameronolivier requested changes

2021-08-30 21:05 UTC, cameronolivier commented on src/modules/UserSkills/UserSkills.constants.ts
> +export const MOCK_SKILLS = [
suggestion: we should delete the mock skills - I dont believe we need them anymore (do a usage check to confirm)

2021-08-30 21:05 UTC, cameronolivier commented on src/modules/Skills/Skills.constants.ts
>  export const FALLBACK_SKILLS_LENGTH = 20
issue: it seems we're repeating these two values - here and in the UserSkills constants

2021-08-30 21:05 UTC, cameronolivier commented on src/modules/UserSkills/UserSkillsForm/UserSkillsForm.constants.ts
> +export const MOCK_USER_SKILLS_LIST = [
suggestion: we should delete this if we aren't using it (And we shouldn't be using it anymore).

2021-08-30 21:05 UTC, cameronolivier commented on src/modules/UserSkills/UserSkillsForm/UserSkillsForm.tsx
> +            items={MOCK_USER_SKILLS_LIST}
we should be using real values going forward.

2021-08-31 01:18 UTC, sciphergfx commented on src/modules/UserSkills/UserSkillsForm/UserSkillsForm.tsx
> +            items={MOCK_USER_SKILLS_LIST}
considering the ticket is  storing user skills credentials in state don't think this is important

2021-08-31 01:19 UTC, sciphergfx commented on src/modules/UserSkills/UserSkillsForm/UserSkillsForm.constants.ts
> +export const MOCK_USER_SKILLS_LIST = [
considering the ticket is storing user skills credentials in state don't think this is important.

2021-08-31 01:19 UTC, sciphergfx commented on src/modules/UserSkills/UserSkillsForm/UserSkillsForm.tsx
> +            items={MOCK_USER_SKILLS_LIST}
there's a ticket that handles this

2021-09-02 20:44 UTC, cameronolivier approved these changes

2021-09-02 20:49 UTC, merged