Yoma-422 - refactor(profile): user logout feature
didx-xyz/yoma-mobile pull request #66
Opened 2021-06-12 14:50 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-422](https://yomaworld.atlassian.net/browse/YOMA-422)

## Work Done
Added user logout 
Fixed lint issues

2021-06-12 22:39 UTC, cameronolivier requested changes

2021-06-16 12:20 UTC, cameronolivier requested changes

2021-06-17 20:55 UTC, cameronolivier requested changes

2021-06-18 20:23 UTC, cameronolivier requested changes

2021-06-20 21:06 UTC, cameronolivier requested changes

2021-06-22 22:06 UTC, cameronolivier requested changes

2021-06-23 21:32 UTC, cameronolivier requested changes

2021-06-23 21:32 UTC, cameronolivier commented on src/modules/App/App.middleware.test.ts
> +      expect(store.dispatch).toBeCalled()
we should be testing that the actions we're expecting to be fired are fired, so it's fine to import in this case.

2021-06-23 21:32 UTC, cameronolivier commented on src/modules/Profile/Profile.container.ts
> +export default connect(mapStateToProps, mapDispatchToProps)(Profile as any)
not a huge issue, but
```js
(Profile as any)
```
shouldn't be necessary

2021-06-23 21:32 UTC, cameronolivier commented on src/redux/middleware.ts
> +import * as appMiddleware from '../modules/App/App.middleware'
can you export the same as the other modules - from the index, please.

2021-06-24 21:31 UTC, cameronolivier requested changes

2021-06-24 21:31 UTC, cameronolivier commented on src/modules/Profile/Profile.container.ts
> +      dispatch(AppActions.resetAppData())
This should dispatch the `AuthActions.logoutUser` action, not the `resetAppData` action.

2021-06-24 21:58 UTC, sciphergfx commented on src/modules/Profile/Profile.container.ts
> +      dispatch(AppActions.resetAppData())
I did it like this previously before this change

2021-06-25 19:23 UTC, cameronolivier requested changes
There's one or 2 still outstanding here, and then the on comment now - but small things, just tidying up.

2021-06-25 19:23 UTC, cameronolivier commented on src/modules/Auth/Auth.reducer.test.ts
> +      // give ... there are no credentials in state
should be 'given' I think that's maybe a typo I started.
and then it should either say `given ... there is data in state` (or simply remove the description, and just have `given ....`

Right now it says given there are no credentials - which definitely isn't what we're testing.

2021-06-28 22:01 UTC, cameronolivier approved these changes, later dismissed

2021-06-30 20:25 UTC, cameronolivier approved these changes

2021-07-01 07:04 UTC, merged