Yoma-435 - refactor(Auth) - registration using api redux middleware
didx-xyz/yoma-mobile pull request #68
Opened 2021-06-18 06:50 UTC by sciphergfx

![](https://media.giphy.com/media/QPQ3xlJhqR1BXl89RG/giphy.gif)
## Scope [YOMA-435](https://yomaworld.atlassian.net/browse/YOMA-435)

## Work Done
- registration using api redux middleware

## Steps to Test 
run the tests.

2021-06-18 21:38 UTC, cameronolivier requested changes
Some changes.

2021-06-20 21:16 UTC, cameronolivier requested changes

2021-06-24 18:30 UTC, cameronolivier requested changes

2021-06-24 18:30 UTC, cameronolivier commented on src/modules/Auth/Auth.utils.ts
> +export const selectLoginCredentialsFromRegistration = pipe(pick(['email', 'password']))
no need for pipe here as you're only using a single util - so can be called on its own.

2021-06-24 21:46 UTC, cameronolivier requested changes

2021-06-24 21:46 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
>        await api.auth
The task here was to make use of the api redux middleware - you're using the api module here. Please refactor the registration to use the middleware - see the Login flow as an example.

So as it stands, this isn't doing what is expected by the story.

Once we have that implemented, we should look at adding the login on success part of it (I think the way we're going to need to do that is through temporarily storing the login credentials in state, and then removing them again.

2021-06-25 10:43 UTC, sciphergfx commented on src/modules/Auth/Auth.types.ts
> +  password?: string
This is temporary, I think we can add the credentials here to the incoming user module.

2021-06-25 10:45 UTC, sciphergfx commented on tests/tests.utils.ts
> +export const createMiddlewareMock = (jest: any, state?: {}) => (middleware: Middleware) => {
Added this to be able to mock state in test

2021-06-25 20:29 UTC, cameronolivier requested changes
a couple of changes

2021-06-25 20:29 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
>        const mockNotification = jest.fn()
can leave this for now - (So OPTIONAL) but functions should really be called Stubs (I think I've messed this up as well) - so should be notificationStub. 

We 'stub' functions and 'mock' data.

2021-06-25 20:29 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +            isTokenRequired: false,
Optional (we can always refactor later) but this isn't required as it's set as a default in the API auth config

2021-06-25 20:29 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
>    async action => {
this action doesn't need to be async

2021-06-25 20:29 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
>        notification('danger', 'Error', action.payload)
we should dispatch a failure action (even if we aren't handling it right now)

2021-06-25 20:29 UTC, cameronolivier commented on src/modules/Auth/Auth.types.ts
> +  password?: string
That or we could add it to a `temp` state endpoint that's blacklisted from persisted state? - not sure if that's a bad idea or not...

2021-06-25 20:29 UTC, cameronolivier commented on tests/tests.utils.ts
> +export const createMiddlewareMock = (jest: any, state?: {}) => (middleware: Middleware) => {
That's cool :) 

you can also do something like this in the test, but yours is actually a cleaner solution
```js
store.getState = jest.fn(() => stateMock)
```

2021-06-27 06:38 UTC, sciphergfx commented on src/modules/Auth/Auth.middleware.ts
>        notification('danger', 'Error', action.payload)
noted @cameronolivier

2021-06-27 16:47 UTC, sciphergfx commented on src/modules/Auth/Auth.middleware.ts
>        notification('danger', 'Error', action.payload)
Please elaborate

2021-06-28 00:48 UTC, sciphergfx commented on src/modules/Auth/Auth.middleware.ts
>        notification('danger', 'Error', action.payload)
Sorry for replying later here. Could you confirm which failure action here?

2021-06-28 07:18 UTC, cameronolivier approved these changes, later dismissed

2021-06-28 07:18 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
>        notification('danger', 'Error', action.payload)
Right. Sorry- misread :(

2021-06-28 07:27 UTC, cameronolivier approved these changes, later dismissed

2021-06-28 07:35 UTC, cameronolivier approved these changes

2021-06-28 07:36 UTC, merged