YOMA-434 - refactor(Auth): add sso registration
didx-xyz/yoma-mobile pull request #70
Opened 2021-06-20 19:01 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-434](https://yomaworld.atlassian.net/browse/YOMA-434)

## Work Done
- Added facebook and google registration and sign in SSO

## Steps to Test
Open the app,  tap facebook button then follow prompts (Google auth provider is still an issue on the backend but it's been configured on the app)

2021-06-25 20:13 UTC, cameronolivier requested changes

2021-06-25 20:13 UTC, cameronolivier commented on src/api/api.middleware.ts
> +          console.log('response', response)
Can you remove the log

2021-06-25 20:13 UTC, cameronolivier commented on src/api/api.middleware.ts
> +          console.log('error', error)
and here

2021-06-25 20:13 UTC, cameronolivier commented on src/components/SocialLogin/SocialLogin.tsx
> +  onLoginWithSocial: (authProvider: string) => void
`authProvider` should be typed to `SocialVariants`.

2021-06-25 20:13 UTC, cameronolivier commented on src/components/SocialRegistration/SocialRegistration.tsx
> +  onRegisterWithSocial: (authProvider: string) => void
likewise here - should be:  `authProvider: SocialVariants`

2021-06-25 20:13 UTC, cameronolivier commented on src/components/SocialRegistration/SocialRegistration.tsx
>  import React from 'react'
This and Login should be the same component- it's doing 100% the same thing in the component - we're just wiring it up to different (login or reg) on implementation.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +        notification('danger', 'Error', error)
I think we should dispatch a failure action here

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +import { selectLoginCredentials, selectRegistrationCredentials } from './Social/Social.utils'
these should be in the auth utils as Social auth is still part of auth.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +import { selectLoginCredentials, selectRegistrationCredentials } from './Social/Social.utils'
I don't think we need a separate Social module

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +            isTokenRequired: false,
this is actually added to the default constants in ApiAuthConstants - so don't need to explicitly set it here.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +        notification('danger', 'Error', error)
we should dispatch a failure action

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +            isTokenRequired: false,
can remove isTokenRequired as it's set in the default for the auth api

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.config.ts
> +    // do nothing when cancelled
we should log a failure action - even if we do nothing with it right now.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.config.ts
> +export const googleSignIn = async () => {
likewise, this needs to be middleware - and can be in the auth middleware I think

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.constants.ts
> +export const GOOGLE_SIGNIN_WEBCLIENT_ID = '1007644634835-8b7vl8u89o7ah0d6pbhbtajarp23h3j0.apps.googleusercontent.com'
I think we can pull all the Social folder into the Auth folder and file structure and flatten everything out.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +  describe('mapFacebookRegistrationData', () => {
I'm not quite sure what this is doing? Should it not be called something like `selectRegistrationCredentialsFromFacebook` or similar? Although I can see how mapping applies here, I think 'select' is a better monicker, as it closely simulates what we're doing in our selectors from state, and have used in other places as well.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +      const mockAuthData = {
and please add some `given when then` for these with more details as to what's expected to happen.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +    it('should return the user registration credentials from google auth payload', () => {
as above.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +  describe('mapFacebookLoginData', () => {
as above

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +  describe('mapGoogleLoginData', () => {
as above.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +        lastName: 'DATA',
when you have multiple fields with 'DATA' values, it's impossible to know what your expected data is referring to or how it works.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +        lastName: 'DATA',
Rather use specific values (like `firstName: 'FIRST NAME'`) so it's obvious how you're deriving data in the expected.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +      const mockMappedData = {
also best is to define this directly in your expected.

```js
expect(result).toEqual({        
        firstName: 'DATA',
        lastName: 'DATA',
        email: 'DATA',
        provider: Providers.Facebook,
        providerKey: 'DATA',
        token: 'TOKEN',
      })
```

Second prize is to call this 'expected' so that it's obvious what you're expecting out of the function.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.test.ts
> +      const mockMappedData = {
I'm sorry I'm being a stickler on the tests - but this is how we get to understand what our code is meant to be doing - if this isn't written properly the codebase becomes harder and harder to reason about.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.ts
> +export const mapFacebookRegistrationData = remap({
it might be simpler to use ramda's `applySpec`, which takes an object and returns a new object with that data,and i already created, but up to you.

so it would be something like this:
```js
const selectGoogleRegistrationCredentials = applySpec({
  provider: always(Providers.Google),
  email: path(['user', 'email']),
  firstName: path(['user', 'givenName']),
  lastName: path(['user', 'familyName']),
  providerKey: always(GOOGLE_SIGNIN_WEBCLIENT_ID),
  token: prop('idToken'),
})
```

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/Social.utils.ts
> +const remap = curry((desc: any, obj: any) =>
if you're keeping this, it needs to be tested.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/index.ts
> +export default (provider: string) => {
I think this will be unnecessary when we refactor the below to use middleware. 

We should be firing off actions that handle side-effects. All app side-effects need to be handled within middleware.

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Auth/Social/index.ts
> +export default (provider: string) => {
Unless specifc usecases where it's not applicable (like redux-persist, although I'm pretty sure that's using redux under the hood)

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Login/Login.tsx
> +  onLoginWithSocial: (details: AuthSocialRegistrationCredentials) => void
Why is this 'RegistrationCredentials' for login? Is that correct (if so, maybe we should rename it to `AuthSocialCredentials` if they are inter-changeable between login and reg

2021-06-25 20:13 UTC, cameronolivier commented on src/modules/Register/Register.tsx
> +        <SocialRegistration onRegisterWithSocial={onRegisterWithSocial} />
This component could probably be called `SocialAuth` or `SSOButtons` or something similar (if you create a single component as suggested above)

2021-06-25 20:13 UTC, cameronolivier commented on src/redux/middleware.ts
> +  authMiddleware.authSocialLoginFlow({ socialAuth: socialAuth, notification: showSimpleMessage }),
Optional, but `socialAuth: socialAuth,` can just be `socialAuth,`

2021-06-27 18:14 UTC, sciphergfx commented on src/components/SocialRegistration/SocialRegistration.tsx
>  import React from 'react'
We can refactor this much later

2021-06-30 21:17 UTC, cameronolivier requested changes

2021-06-30 21:17 UTC, cameronolivier commented on src/components/SocialSSO/SocialSSO.tsx
> +import React from 'react'
I think this is a little unnecessarily named -what I mean is it means Social Social Sign On, right?
So, I think SSO is actually good, or maybe SSOAuth?

2021-06-30 21:17 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +    it('should correctly send a notification to the user', async () => {
these shouldn't need to be async / await (please keep an eye on this in general)

2021-06-30 21:17 UTC, cameronolivier commented on src/modules/Auth/Social/Social.config.ts
> +export const facebookSignIn = async () => {
Why isn't this in the middleware - I think that's the best place for it?  These side-effects should be handled within a middleware - so that at least we can catch fails with failure actions

2021-06-30 21:17 UTC, cameronolivier commented on src/redux/store.ts
> +          authActions.authLoginSuccess.type,
why are we ignoring these new actions?

2021-07-01 15:13 UTC, sciphergfx commented on src/components/SocialSSO/SocialSSO.tsx
> +import React from 'react'
noted

2021-07-02 06:30 UTC, sciphergfx commented on src/modules/Auth/Social/Social.config.ts
> +export const facebookSignIn = async () => {
the function is called in the middleware @cameronolivier

2021-07-02 10:36 UTC, sciphergfx commented on src/redux/store.ts
> +          authActions.authLoginSuccess.type,
Feedback from SSO auth has unserialised contents

2021-07-06 21:45 UTC, cameronolivier requested changes

2021-07-06 21:45 UTC, cameronolivier commented on src/components/SSO/index.ts
> +import SocialRegistration from './SSO'
rename to `import SSO from './SSO'`

2021-07-06 21:45 UTC, cameronolivier commented on src/components/index.ts
> +import SocialRegistration from './SSO'
We need to stop using this index file to export-  It's better to import directly from the component module as this creates circular references. This is a legacy thing that I think we need to move away from.

2021-07-06 21:46 UTC, cameronolivier requested changes
I've tested this locally - and both Google and Facebook registrations are failing - is this an issue with the API? 

I see it seems like Google SSO reg works... as in it gets the data back from google, but fails on submitting to the API so there's something that's not working here.

2021-07-07 10:01 UTC, sciphergfx commented on src/components/index.ts
> +import SocialRegistration from './SSO'
Noted, Do we create a separate branch to correct this, or you want me to effect it on this branch?

2021-07-07 18:40 UTC, cameronolivier requested changes

2021-07-07 18:40 UTC, cameronolivier commented on src/components/index.ts
> +import SSO from './SSO'
please don't export from here - rather export from the component module itself. This can cause super annoying circular dependency issues.

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +            isTokenRequired: false,
You can remove this - all of the auth configs are preset to have `isTokenRequired: false,`:
```js
// from api/auth/auth.constants.ts

//This is the base Auth config object, merged into every endpoint config:
export const AUTH_CONFIG: Partial<ApiMeta> = {
  client: ApiClients.Auth,
  method: ApiMethods.Post,
  isTokenRequired: false,
}
```

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +      // given ... the action is fired
these tests should be broken into the following 
given - the state we expect the app to be in when we're testing (this includes redux state, etc)
when - this is the action - so this is what we want to be testing
then -  this is what we expect to happen _when_ the thing we're testing happens.

given when then should be in user-readable format - ie Clayton should be able to read it. Clayton should even be able to write the given/when/then criteria - which we fulfill in code. so we should avoid using language that simply reflects _what_ the code is _doing_ and rather reflect what the user/stakeholder needs from it. 

Please chat to me tomorrow morning if you're not quite sure how this works and we can walk through it.

We should strive to have all our tests follow this flow.

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/index.ts
> +export default (provider: string) => {
OPTIONAL, but also I really don't want switches in our code if we can help it - a better way to write this is with a simple map function, so we avoid switch altogether:
```js
const ssoProviders = {
  facebook: () => facebookSignIn(),
  goodle: () => googleSignIn(),
}
```

Then in usage you just say 
```js
 ssoProviders[provider]()
```

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.utils.ts
> +export const selectRegistrationCredentialsFromFacebook = applySpec({
should be `extract...`  - and likewise below

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.utils.ts
> +export const selectSocialLoginCredentials = (authProvider: Providers, authData: any) => {
same as comment on switches below - if you export this as an object, the 'provider' becomes the key, and you can simply call it as :
```js
selectSocialLoginCredentials[provider](authData)
```

2021-07-07 18:40 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.config.ts
> +export const facebookSignIn = async () => {
I keep coming back to it - this needs to be in middleware. this is not the place to be doing this. 

Please refactor. 

I get there may seem to be some similarities with the api.config - but we're not actually calling any async/ data functions in the config- I'm just front-loading/setting up the api instance that is then only called within the middleware. 

The way you've set this up is an antipattern. 

Sorry to circle back to this so late in the game, but every time I come back to this - it just doesn't sit right with the rest of the architecture of the app - and I suspect it might be some of the reason we're having issues in the app flow.

2021-07-07 19:07 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +      // given ... the action is fired
that said ^^ I'm happy with flexibility as we move towards this everywhere - let's aim at getting better with this - at the moment the test quality is a bit all over the place - some of the tests are spot on, others aren't really structured well - so I'll give a bit of pushback, but I'm not going to stop it going through for now. Just please focus on this getting better. and I'll keep giving feedback where it could be better, but as long as we're testing the right things - and what we're testing covers the functionality, I'm going to stop requesting changes to tests as something that stops merging (for now) - I think it's something we can work towards.

2021-07-07 23:44 UTC, sciphergfx commented on src/modules/Auth/SSOAuth/SSOAuth.config.ts
> +export const facebookSignIn = async () => {
I disagree the way it's wired up is an anti-pattern, happy to chat about it.

2021-07-07 23:46 UTC, sciphergfx commented on src/modules/Auth/SSOAuth/index.ts
> +export default (provider: string) => {
This is valid, similarly having to just call 
```js
 ssoProviders(provider)
```
looks cleaner

2021-07-10 20:47 UTC, cameronolivier commented on src/redux/store.ts
> +          authActions.authLoginSuccess.type,
Can we not extract the functions from the payload before dispatching it in the action? I'd rather sanitize the data if possible than add actions here unnecessarily.

2021-07-10 20:50 UTC, cameronolivier commented on src/components/index.ts
> +import SocialRegistration from './SSO'
I think we should refactor as we go, for now. Correct it when we get to it and don't add new, but we should do the big refactor in a separate branch, with a jira ticket, definitely.

2021-07-12 21:33 UTC, cameronolivier requested changes
Currently when we cancel, it throws an error:
<img width="454" alt="Screenshot 2021-07-12 at 22 53 01" src="https://user-images.githubusercontent.com/1424561/125354287-ec42cb80-e363-11eb-9903-0e0df4a62126.png">

We shouldn't be throwing an error on a cancelled login/registration.

Also, I cancelled facebook, but the success action was fired:
<img width="494" alt="Screenshot 2021-07-12 at 23 16 55" src="https://user-images.githubusercontent.com/1424561/125357016-5315b400-e367-11eb-8e02-a6e3b9dafe52.png">
The same happens with social logins. 
We should probably log a cancelled action - and ignore it. (or simply ignore it) 

Then I tried to register with Facebook.- the SSO part went fine but our API returned with this error:
```js
success: false
code: 400
message: "The LastName field is required., The FirstName field is required."
```
So it doesn't look like the correct information is being submitted.

Then have found some further issues in the code. Mostly naming convention stuff. As there are still issues to iron out, please do them in this PR as well.

And please run through your PRs and make sure that these things are correct before you request a review.

2021-07-12 21:33 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.ts
> +  ({ SSOAuth }: { SSOAuth: Function; notification: typeof showSimpleMessage }): Middleware =>
we shouldn't be uppercasing utils/dependencies functions (as you know :) ) - I think we both just missed this.

2021-07-12 21:33 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.constants.ts
> +export const GOOGLE_SIGNIN_WEBCLIENT_ID = '1007644634835-8b7vl8u89o7ah0d6pbhbtajarp23h3j0.apps.googleusercontent.com'
is this a public-facing id or something we need to save securely? 
If it's public-facing it should be in our ENV config.
if it needs to be saved securely, then we need to set it in the Circle CI config (and in our 1pass details)

2021-07-12 21:33 UTC, cameronolivier commented on src/vendor.d.ts
> +  export function applySpec(...rest: any[]): any[]
remove the `[]` off the end:
```js
export function applySpec(...rest: any[]): any
```

Will fix the linting errors in the utils.

2021-07-12 21:33 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.utils.ts
> +import { facebookAuthDependencies, googleAuthDependencies } from './../../SSOAuth/SSOAuth.types'
fix this import, please

2021-07-12 21:33 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.utils.ts
> +import { facebookAuthDependencies, googleAuthDependencies } from './../../SSOAuth/SSOAuth.types'
and types should be `PascalCase`

2021-07-12 21:56 UTC, cameronolivier requested changes

2021-07-12 21:56 UTC, cameronolivier commented on src/api/api.utils.ts
> +export const generateEndpoint: GenerateEndpoint = join('/')
I think this was a merge issue - this util can be removed - it is no longer used - I removed it in a previous PR.

2021-07-12 21:56 UTC, cameronolivier commented on src/api/api.utils.ts
> +import { ApiCall, ApiClientArgs, ApiMeta, GenerateEndpoint, PrepareApiRequestData } from './api.types'
You can remove the GenerateEndpoint as well - as it actually no longer exists.

2021-07-12 21:56 UTC, cameronolivier commented on src/api/api.utils.ts
> +export const generateEndpoint: GenerateEndpoint = join('/')
I presume that you didn't intend to make any changes to this file - so could roll back to whatever state develop is in for this file - and that should be fine.

2021-07-12 21:56 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +import { authSocialLoginFailure, authSocialRegistrationFailure, INITIAL_STATE } from 'modules/Auth/Auth.reducer'
please fix the imports here - this is the wrong place to be importing from - also we are already importing from the reducer file, below - so merge in with that, please.

2021-07-12 21:56 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +      // then ... the notification should be calleds
remove the rogue s

2021-07-12 21:56 UTC, cameronolivier commented on src/modules/Auth/SSOAuth/SSOAuth.utils.ts
> +    if (!loginResponse.isCancelled) {
I've mentioned this elsewhere, but we aren't handling if this is cancelled in anyway (and so our middleware fires success). It should simply revert quietly.

2021-07-13 06:34 UTC, sciphergfx commented on src/modules/Auth/SSOAuth/SSOAuth.constants.ts
> +export const GOOGLE_SIGNIN_WEBCLIENT_ID = '1007644634835-8b7vl8u89o7ah0d6pbhbtajarp23h3j0.apps.googleusercontent.com'
I'm not sure if it need to be saved securely, but we can if necessary. It acts more like a url would

2021-07-13 19:17 UTC, cameronolivier requested changes
The primary thing here is: we should not be throwing an error if the user cancels. It should fail silently. We can dispatch a cancelled action if we want to deal with it down the line, but not an error.

2021-07-13 19:17 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +import { authSocialLoginFailure, authSocialRegistrationFailure, INITIAL_STATE } from 'modules/Auth/Auth.reducer'
This still needs to be done. Add it with the below import from the Auth reducer

2021-07-13 19:17 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.types.ts
> +  fbLoginManager: typeof LoginManager | any
if you or as `any` then you may as well just make it `any`.

2021-07-13 19:17 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.utils.test.ts
> +    it('should correctly handle cancelled google auth', async () => {
we don't want to throw an error if the user cancels. it's not an error. it's just a canceled event. So if you want to dispatch a canceled action so we have access to that information, then I think that's a good idea - but otherwise it should just fail silently. We shouldn't fire a success or an error - because it is neither.

2021-07-13 19:17 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.utils.ts
> +      throw new Error(fbAuthCancelledErrorMessage)
as mentioned above - don't throw an error on cancel. return false maybe and handle that or ignore that in the middleware - but a user cancelling is not an error event.

2021-07-13 19:17 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.utils.ts
> +export const onGoogleAuth = async ({ googleSignIn }: GoogleAuthDependencies) => {
how are we handling a cancelled event with google?

2021-07-13 21:13 UTC, cameronolivier requested changes
just need to test the failing states of the sso auth utils

2021-07-13 21:13 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.utils.test.ts
> +  describe('onFacebookAuth', () => {
we need to add a test for if it errors out (that if any of our dependencies throw an error, we're catching it as expected)

2021-07-13 21:13 UTC, cameronolivier commented on src/modules/SSOAuth/SSOAuth.utils.test.ts
> +  describe('onGoogleAuth', () => {
as with facebook we also need to test that we are throwing an error when we'd expect to throw one.

2021-07-14 20:34 UTC, cameronolivier submitted a review, later dismissed

2021-07-14 20:34 UTC, cameronolivier commented on src/modules/Auth/Auth.middleware.test.ts
> +import { authSocialLoginFailure, authSocialRegistrationFailure, INITIAL_STATE } from 'modules/Auth/Auth.reducer'
@sciphergfx this needs to be fixed. But let's refactor when we next touch this file.

2021-07-14 20:34 UTC, cameronolivier commented on src/modules/SSOAuth/index.ts
> +export default (provider: string) => {
crap I missed this.
we should define this function, and it should be tested. 

But let's leave it - and we can update when we refactor SSO

2021-07-15 20:29 UTC, cameronolivier approved these changes, later dismissed

2021-07-17 20:15 UTC, cameronolivier approved these changes

2021-07-17 20:15 UTC, cameronolivier commented on src/modules/Register/Register.tsx
> -import LargeHeader from '../../components/LargeHeader'
this is the preferred way to import. 
but happy for now.

2021-07-18 03:21 UTC, merged