Yoma-436: refactor(User): user data in profile view - DRAFT
didx-xyz/yoma-mobile pull request #73
Opened 2021-06-28 04:01 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-436](https://yomaworld.atlassian.net/browse/YOMA-436)

## Work Done

## Steps to Test

    
## Screenshots

2021-06-29 20:54 UTC, cameronolivier requested changes
just a smallish thing

2021-06-29 20:54 UTC, cameronolivier commented on src/modules/Profile/Profile.container.tsx
> +const mapStateToProps = (state: RootState) => {
as with others, you should create a Profile.selector that handles mapping data from state to props.

2021-07-02 19:39 UTC, cameronolivier requested changes
a couple small changes - but otherwise good

2021-07-02 19:39 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      // then ...validate setUserOnAuthFlow
we should also check that store.dispatch was called. - just check it was called, that's all we need to do here.

2021-07-02 19:39 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +  async action => {
no need for async

2021-07-02 19:39 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      await invoke(action)
can remove async await

2021-07-04 22:30 UTC, cameronolivier requested changes

2021-07-04 22:30 UTC, cameronolivier commented on src/modules/User/User.reducer.ts
> +export const setUserCredentials = createAction<UserResponse>(`${name} Set User Credentials`)
std naming convention for `createAction()` is to be: `[<name of module>] <name of action>`

eg: 
```js
export const setUserCredentials = createAction<UserResponse>(`${name} setUserCredentials`)
```

This keeps it simple and a 1:1 reference in the logger to the js action name.

2021-07-05 21:26 UTC, cameronolivier requested changes

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      await invoke(action)
this hasn't been done?

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      dispatch(setUserCredentials(credentials))
And this should be `setUser`.

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserCredentialsFromLoginPayload(action)
this probably isn't 'credentials' but rather user data = simply 'user' - credentials are username/password.

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +import { selectUserCredentialsFromLoginPayload } from './User.utils'
as below - remove 'credentials' as we're getting user data from auth success, not credentials, correct?

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.reducer.test.ts
> +  describe('setUserCredentials', () => {
follow action renaming here as well (`setUser`)

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectUserState = (state: RootState) => state.user
this should just be `selectUser` - state is superfluous here - and creates unnecessary ambiguity for if we ever have a 'user state' (ie subscribed, or onboarded, or what-have-you) - that said, in that event, I think user status might be better- but the Api might dictate.

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const selectUserCredentialsFromLoginPayload = pipe(path(['payload', 'data', 'data', 'user']))
as mentioned above - this should be named correctly to what it's doing - 'credentials' is incorrect so should be removed. 

```js
selectUserFromLoginPayload
```

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/User/User.reducer.ts
> +export const INITIAL_STATE = {}
I think we should create an initial state that reflects the user state - but with empty data. 
So it needs to reflect the properties we expect the state to contain, with useful default values:
```js
id:"",
firstName:"",
lastName:"",
phoneNumber:null,
biography:null,
countryAlpha2:"",
email:"",
zltoWalletId:null,
zltoBalance:0,
covidChallengeCertificateURL:null,
tideChallengeCertificateURL:null,
photoURL:null,
organisationId:null,
organisation:null,
organisationVerified:false,
createdAt:"", // (or null)
lastLogin:"", // (or null)
```

2021-07-05 21:26 UTC, cameronolivier commented on src/modules/Profile/Profile.selector.tsx
> +  user,
do we need the entire user object? We should only be bringing in those values that we will be needing in this view. 
Individually, or in a user object. So as individual props:
```js
export default createSelector( ... firstName, lastName, number... => ({
 firstName,
 lastName,
 number,
 ...
})
```
or in a user object: 
```js
export default createSelector( ... firstName, lastName, number... => ({
 user: {
   firstName,
   lastName,
   number,
   ...
 },
 ...
})
```

2021-07-05 21:30 UTC, cameronolivier requested changes

2021-07-05 21:30 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectUserState = (state: RootState) => state.user
It should also be tested. 

All selectors need to have tests.

2021-07-06 04:39 UTC, sciphergfx commented on src/modules/Profile/Profile.selector.tsx
> +  user,
I'm not sure if this matters, as it creates a reference for all user (updated) credentials. We can equally use other props else where in the application @cameronolivier

2021-07-06 04:40 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +      await invoke(action)
I missed this one

2021-07-06 04:43 UTC, sciphergfx commented on src/modules/User/User.selector.ts
> +export const selectUserState = (state: RootState) => state.user
I purposely don't create tests for rootState selector, as it'll always return same prop as defined in the reducer, but happy to add one @cameronolivier

2021-07-06 14:55 UTC, sciphergfx commented on src/modules/User/User.reducer.ts
> +export const INITIAL_STATE = {}
If we take this approach then we should initiate other reducer state values across, Your thoughts? @cameronolivier

2021-07-06 15:02 UTC, sciphergfx commented on src/modules/Profile/Profile.selector.tsx
> +  user,
I'll implement this on YOMA-437

2021-07-06 20:24 UTC, cameronolivier requested changes

2021-07-06 20:24 UTC, cameronolivier commented on src/modules/Profile/Profile.selector.tsx
> +  user,
Please do the changes here. Doing changes in future PRs makes it really difficult to track comments and changes across PRs.

2021-07-06 20:24 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const selectUserFromLoginPayload = pipe(path(['payload', 'data', 'data', 'user']))
no need for a pipe here as it's just the 1 fn

2021-07-06 20:24 UTC, cameronolivier commented on src/modules/User/User.reducer.ts
> +export const INITIAL_STATE = {}
yes 100%. 

the only place I think we shouldn't (At least now) is the auth reducer purely because it's auth. But even there we could create the object - but yes, we should have our default INITIAL_STATE represent what the default values should be for each of our state properties

2021-07-06 20:24 UTC, cameronolivier commented on src/modules/User/User.reducer.test.ts
> +      const state = {}
state is RootState - so should reflect the state, like:
```js
const state = {
  auth: AUTH_INITIAL_STATE,
  user: USER_INITIAL_STATE,
}
```

2021-07-06 20:24 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserFromLoginPayload(action)
small thing - but rename 'credentials' as well - to `user`.

2021-07-07 09:03 UTC, sciphergfx commented on src/modules/User/User.reducer.test.ts
> +      const state = {}
In order to keep consistency, I think this change is required in many places, why don't we create a branch and effect them? I see PR85 has rootStateFixture, We can use that here? @cameronolivier

2021-07-07 17:33 UTC, cameronolivier submitted a review, later dismissed

2021-07-07 18:43 UTC, cameronolivier approved these changes

2021-07-07 23:34 UTC, merged