Yoma-449 - refactor(About) - About - should correctly display current data
didx-xyz/yoma-mobile pull request #78
Opened 2021-07-01 11:05 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-449](https://yomaworld.atlassian.net/browse/YOMA-449)

## Work Done
Wired biography content to about widget

2021-07-02 19:50 UTC, cameronolivier requested changes

2021-07-02 19:50 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +import selector from 'modules/About/About.selector'
please import this locally `import selector from './About.selector'`

2021-07-02 19:50 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +    it('should select props as expected when available in state', () => {
Add a test for empty state (reflecting user: INITIAL_STATE)

2021-07-04 07:42 UTC, sciphergfx commented on src/modules/About/About.container.tsx
> +import selector from 'modules/About/About.selector'
my IDE auto import seem to be causing this issue. I'll make changes, thanks

2021-07-04 07:42 UTC, sciphergfx commented on src/modules/About/About.selector.test.ts
> +    it('should select props as expected when available in state', () => {
noted

2021-07-04 22:23 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +import selector from 'modules/About/About.selector'
I think it's a babel import thing that Ranjit added (that I'd rather remove) - but it's going to affect multiple files - so we need to keep an eye on it

2021-07-08 19:39 UTC, cameronolivier approved these changes, later dismissed

2021-07-08 20:15 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectBiography = createSelector(selectUser, propOr('', 'biography'))
you don't need to use prop or if your initial reducer state is correct - because even if you don't have data, it'll always be an empty string - so what I'd suggest is set 'biography' to '' in the INITIAL_STATE object for the user.

Happy for you to do this in a follow up PR.

2021-07-08 20:15 UTC, cameronolivier approved these changes
Left a comment - please do this in #82

2021-07-08 20:53 UTC, merged