refactor(DigitalCV): MyCV - Display real data in About widget
didx-xyz/yoma-mobile pull request #82
Opened 2021-07-01 16:10 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-442](https://yomaworld.atlassian.net/browse/YOMA-442)

## Work Done
 - Display real data in About widget

2021-07-02 20:04 UTC, cameronolivier reviewed
Happy with this, just want to get `YOMA-449` branch in and then I'll run it on device

2021-07-05 21:40 UTC, cameronolivier requested changes
Picked up a couple small things.

2021-07-05 21:40 UTC, cameronolivier commented on src/modules/DigitalCv/DigitalCv.container.tsx
> +import selector from 'modules/About/About.selector'
you're pulling this in from the wrong place - should be using the DigitalCV selector

2021-07-05 21:40 UTC, cameronolivier commented on src/modules/DigitalCv/DigitalCv.selector.ts
> +import * as userSelectors from '../User/User.selector'
we should be importing this from the module index, not the internal selector.

2021-07-07 10:10 UTC, sciphergfx commented on src/modules/DigitalCv/DigitalCv.selector.ts
> +import * as userSelectors from '../User/User.selector'
Do you mean we introduce 
```js
export { actions, reducer, middleware, selectors }
```

2021-07-10 21:22 UTC, cameronolivier requested changes
We need a couple of changes around tests.

2021-07-10 21:22 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +      expect(result).toEqual({ biography: undefined })
This tests when state (root state) is an entirely empty object - that would never be the case. state will always be an initial state object, or a populated state. 

So you should be wrapping selectors with `rootStateFixture()` and adding in data where you need it. 

So `ln 8` should be something like: 
```js
const stateMock = rootStateFixture({
        user: {
          id: 'USER_ID',
          firstName: 'FIRST_NAME',
          lastName: 'LAST_NAME',
          phoneNumber: 'PHONE_NUMBER',
          biography: 'BIOGRAPHY',
          countryAlpha2: 'COUNTRY_ALPHA2',
          email: 'USER_EMAIL@SOMEWHERE.TEST',
          zltoWalletId: 'ZLTO_WALLET_ID',
          zltoBalance: 1000,
          covidChallengeCertificateURL: 'COVID_CHALLENGE_CERTIFICATE_URL',
          tideChallengeCertificateURL: 'TIDE_CHALLENGE_CERTIFICATE_URL',
          photoURL: 'PHOTO_URL',
          role: 'ROLE',
          organisation: 'ORGANISATION',
          createdAt: 'CREATED_AT',
          lastLogin: 'LAST_LOGIN',
        },
      })
```

2021-07-10 21:22 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +      expect(result).toEqual({ biography: undefined })
And `ln 33`, you should be simply:
```js
const stateMock = rootStateFixture()
``` 
This will set up the state mock to be the equivalent of
```js
{
  about: ABOUT_INITIAL_STATE,
  user: USER_INITIAL_STATE,
}
```
which is what we'd expect an empty redux state to look like.

2021-07-10 21:22 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +      expect(result).toEqual({ biography: undefined })
Then we can remove this, because it doesn't test a state we could expect to have in the app. 
```js
it('should handle empty state if props not available', () => {
      // given ...
      const state = {}
      // when ... we call the selector
      const result = SUT.default(state)
      // then ... should return result as expected
      expect(result).toEqual({ biography: undefined })
    })
```

2021-07-10 21:22 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectBiography = createSelector(selectUser, prop('biography'))
we need to add a test for an empty user state here (well an `INITIAL_STATE`) to test that we're returning an empty string for the `biography` property.

2021-07-10 21:22 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectBiography = createSelector(selectUser, prop('biography'))
We don't have one yet.

2021-07-12 22:02 UTC, cameronolivier submitted a review, later dismissed

2021-07-12 22:02 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +import { rootStateFixture } from './../../redux/redux.test.fixtures'
we don't need this `./../....` in front of import strings. can simply go `../....`

2021-07-12 22:02 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +import { rootStateFixture } from './../../redux/redux.test.fixtures'
I'm happy to let it slide for now - but you need to be catching these things yourself before requesting a review.

2021-07-12 22:32 UTC, cameronolivier requested changes
I can't really test this because I don't have any data - so need the other task in first (for editing the about information) before I could confirm that this is working. Have you been able to test it @sciphergfx ?

2021-07-12 22:32 UTC, cameronolivier commented on src/modules/DigitalCv/DigitalCv.tsx
> -import CvCard from '../../components/CvCard'
This is the correct import - importing from 'components' breaks the app.

2021-07-12 22:32 UTC, cameronolivier commented on src/components/CvCard/CvCard.tsx
> +  text: string
There are issues in implementing this card in the DigitalCV because this field is required. Initially the user won't have text, but more importantly - this breaks all the other CVCards in the DigitalCV view.

So options are - set a default text value of '' for all the cards in DigitalCV, or make this optional.  If we always expect there to be some text here (even if it might be '') then keep it as required. 

BTW - what are we going to do with the Education or MySkills sections where the content isn't text, but an array of presumably objects - to display the different credentials. I think that text might not be the correct property. 

I'd call the `text` field something like 'content' to cater for the list of info OR the string in the case of biography and the `defaultText` - `fallbackText` rather as 'defaultText' implies that we're expecting text and this is the default - fallback is frequently used for when there is no value (regardless of the data) - placeholderText could also work.

2021-07-13 07:13 UTC, sciphergfx commented on src/modules/DigitalCv/DigitalCv.tsx
> -import CvCard from '../../components/CvCard'
Weird, sorted this too. I'll revert

2021-07-13 19:43 UTC, cameronolivier requested changes
small changes - basically just need to revert the changes in Body.tsx text

2021-07-13 19:43 UTC, cameronolivier commented on src/components/CvCard/CvCard.tsx
> +const renderTextContent = (content: string, defaultText: string) => (
happy with this for now. 

Honestly the easiest I think would have been to pass the content as children, and show a fallback if the children were null/empty. I know I mentioned content - I realise that's wrong. The designs are different for each credential - so it's probably best to pass in as children and we can handle the list renders in separate components that cater to each of the specific layouts. 
<img width="379" alt="Screenshot 2021-07-13 at 21 22 29" src="https://user-images.githubusercontent.com/1424561/125512524-823bd168-3bd6-4209-8937-c6aa4df4fd1f.png">


THAT said, let's get back to this when we get to those components. For now, as long as the about text is being correctly rendered in the CvCard, I'm happy.

2021-07-13 19:43 UTC, cameronolivier commented on src/components/Typography/Body/Body.tsx
> +    align?: TextAlign
there is no need to add this as `align` is already exposed on the Text component in `Typography/Text.tsx` and all child components (Body, Header, etc) accept all the same props as the base text component.

2021-07-13 19:43 UTC, cameronolivier commented on src/components/Typography/Body/Body.tsx
> +    align?: TextAlign
Please revert these changes.

2021-07-13 19:43 UTC, cameronolivier commented on src/components/Typography/Body/Body.tsx
> +    align?: TextAlign
This works: 
```js
<Text.Body align={TextAlign.left}>Hello World</Text.Body>
```

2021-07-13 19:57 UTC, sciphergfx commented on src/components/Typography/Body/Body.tsx
> +    align?: TextAlign
There's a lint error here

2021-07-15 20:34 UTC, cameronolivier commented on src/modules/DigitalCv/DigitalCv.selector.ts
> +import * as userSelectors from '../User/User.selector'
yes. Where possible - but I think where we end up with circle imports, then we can import directly from the selector file.

2021-07-20 21:09 UTC, cameronolivier reviewed
Not sure why the selectUser test was deleted. We shouldn't be?

2021-07-20 21:09 UTC, cameronolivier commented on src/modules/User/User.selector.test.ts
> -  describe('selectUser ', () => {
Why are we deleting this test?

2021-07-21 04:45 UTC, sciphergfx commented on src/modules/User/User.selector.test.ts
> -  describe('selectUser ', () => {
It appeared twice, it's down below. Can reposition it

2021-07-21 15:33 UTC, cameronolivier approved these changes

2021-07-21 15:33 UTC, cameronolivier commented on src/modules/User/User.selector.test.ts
> -  describe('selectUser ', () => {
Ok. It should be up here - but we can do that another time.

2021-07-22 00:32 UTC, merged