YOMA-480 - refactor(App): Error running app: Module AppRegistry is not a registered callable module
didx-xyz/yoma-mobile pull request #87
Opened 2021-07-04 08:12 UTC by sciphergfx

![](gifSrc)
## Scope [YOMA-480](https://yomaworld.atlassian.net/browse/YOMA-480)

## Work Done
- imported App entry file directly into index.js
- Back navigation crashing device on auth screens (this icon needs to be removed from UI)

2021-07-04 20:29 UTC, cameronolivier requested changes

2021-07-04 20:29 UTC, cameronolivier commented on index.js
> +import App from './src/modules/App/App'
this should be reverted.

2021-07-04 20:29 UTC, cameronolivier commented on src/modules/App/index.ts
> +import * as middleware from './App.middleware'
have you removed the App export from the index?

2021-07-04 21:57 UTC, cameronolivier commented on src/modules/App/index.ts
> +import * as middleware from './App.middleware'
I see this is what fixed the issue - however, I'm not happy with this workaround.  I don't think we're fixing anything here- we're simply avoiding it - which means it comes back to bite us at some point. 

I reverted your changes on the `index.js` <> `App.ts` - and it seems to be a bit better (although I still intermittently got that ui wait issue)

```js
import { RNLocalize, setI18nConfig } from 'locales/i18n'
import React, { useEffect } from 'react'
import FlashMessage from 'react-native-flash-message'

import AppNavigation from '../AppNavigation'

setI18nConfig()

const App = () => {
  useEffect(() => {
    RNLocalize.addEventListener('change', setI18nConfig)
    return () => {
      RNLocalize.removeEventListener('change', setI18nConfig)
    }
  }, [])

  return (
    <>
      <AppNavigation />
      <FlashMessage position="top" />
    </>
  )
}

export default App

```

```js
import React from 'react'
import { AppRegistry } from 'react-native'
import 'react-native-gesture-handler'
import { config } from './config'
import App from './src/modules/App'
import { persistor, store } from './src/redux/store'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'

const Root = () => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <App />
    </PersistGate>
  </Provider>
)

AppRegistry.registerComponent(config.application.name, () => Root)

```
but I kept the App export in `App/index.ts`

I think this might a step towards a fix.

2021-07-05 05:37 UTC, sciphergfx commented on src/modules/App/index.ts
> +import * as middleware from './App.middleware'
> have you removed the App export from the index?

Yes I did, We're getting errors when exported as default in App/index.ts

2021-07-05 05:42 UTC, sciphergfx commented on src/modules/App/index.ts
> +import * as middleware from './App.middleware'
Picked up the lag as well, but I can update changes as above

2021-07-05 21:30 UTC, cameronolivier approved these changes

2021-07-06 06:30 UTC, merged