Yoma-450 - refactor(User): about should correctly save any edits to backend
didx-xyz/yoma-mobile pull request #88
Opened 2021-07-05 05:29 UTC by sciphergfx

![](http://gph.is/2dgEC8c)
## Scope [YOMA-450](https://yomaworld.atlassian.net/browse/YOMA-450)

## Work Done

## Steps to Test

    
## Screenshots

2021-07-05 22:19 UTC, cameronolivier requested changes
quite a few changes required.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +import selector from 'modules/About/About.selector'
fix this import please.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +import * as UserActions from '../User/User.reducer'
import from the module index rather

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +    onUpdateUserCredentials: (biography: string) => {
this should be `onUpdateUser` as mentioned in PR for user data

However, I'd actually say it should be `onUpdateBiography` or `onUpdateAbout` as that's more specifically what we're updating here.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', async () => {
this wouldn't be async

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      const action = updateUserCredentials(updateCredentials)
this should be `updateUser` - we aren't dealing with credentials here.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', async () => {
we need more test cases. 

1. should handle being called
2. should submit the updated user biography (testing that it calls our api middleware with the correct information)

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', () => {
as above, we want a second test handling the expected success state.
I know this is a bit tedious, but we want to
1. test it's handling being called
2. test that the functionality of our middleware is succeeding as expected 
3. (optionally) test that it fails and we catch it in an expected manner
4. (any other specific use cases that might arise)

But we want to explicitly be testing specific things each time.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const updateUserCredentialsFlow: Middleware =
As mentioned above -remove credentials.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +  async action => {
this isn't actually an async action as the api middleware handles the async aspect.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const userId = selectUserIdFromUserCredentials(state)
should just be named `selectUserId` and you can use a standard selector for that.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const updateUserCredentialsSuccessFlow =
again - remove credentials

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +export const updateUserCredentialsFailureFlow =
again remove credentials

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      const userId = selectUserIdFromUserCredentials(mockState)
you don't need to do this - you have the USER_ID value already above.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      const mockAction = {
this test is way too complicated. 

we don't need the mockAction. 
You can simply set the action payload here:
```js
const action = updateUserCredentials('A PAYLOAD')
```
or if you want to be more specific, you could do: 
```js
const action = updateUserCredentials({biography: 'A BIOGRAPHY'})
```

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      const userUpdateCredentials = selectUserUpdateCredentials(mockAction)(mockState)
we shouldn't need this.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +            endpoint: userId,
we can just set this, we don't need to use the util - we already have it above in the mockState: 
```js
id: 'USER_ID',
```

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', async () => {
So please follow the same testing flow (as detailed above) as you've done in all the other middleware.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +          userUpdateCredentials,
we can just set this again in text - the more explicit we are with tests the easier it is to see what's going on, and understand what we're trying to test. 

So if you take my example above, this will simple either be a string:
```js
 'A PAYLOAD'
```
or an object:
```js
{biography: 'A BIOGRAPHY'}
```

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectUserUpdateCredentials = (action: any) =>
the selector isn't the place for a util to extract data from the api response. 

only functions (selectors) that act on state data should be here.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +    pipe(
as an aside, I'm unsure why you're specifically only returning these values from the api call? I'd suggest you simply update the user object with the user data you get back - which is simple enough to extract - and removes the need for this map/apply spec.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserCredentialsFromUpdatePayload(action)
I think all you need to do here is get the data from the payload and dispatch off a `setUser` action with the user object.

2021-07-05 22:19 UTC, cameronolivier commented on src/modules/User/User.types.ts
> +export interface UserCredentialsPayload {
this is not the credentials, this is the user.

2021-07-06 04:53 UTC, sciphergfx commented on src/modules/User/User.selector.ts
> +    pipe(
If user object is updated, then that change is persisted. (even if update operation fails)

2021-07-06 04:56 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', async () => {
noted

2021-07-06 11:13 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserUpdateCredentials(action)(state)
```js
const user = selectUser(state)
const userProfile = pick(['lastName', ...])(user)
const payload = mergeRight(userProfile, action.payload)
```
or as a util:
```js
const createUserProfilePayload = state => payload => pipe(
 selectUser, 
 pick(['lastName', ...]),
 mergeLeft(action.payload)
)(state)
```

2021-07-06 18:39 UTC, sciphergfx commented on src/modules/About/About.container.tsx
> +import * as UserActions from '../User/User.reducer'
this change cuts across 3 branches, I think it makes sense to implement on base x branch (YOMA-436) before merge with develop.

2021-07-06 21:04 UTC, cameronolivier requested changes

2021-07-06 21:04 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +      const credentials = selectUserFromUpdatePayload(action)
also credentials rename to user

2021-07-06 21:04 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserFromUpdatePayload(action)
please rename to 'user'

2021-07-06 21:04 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = selectUserFromUpdatePayload(action)
This fn should be called `extractUser`, as this one is specifically doing that. On second thought, I think `extractUserFromUserUpdateSuccess` is the best (I can come up with) for now - as we would have a similar (but different) `extract` function for getting the user object from the Auth success.

2021-07-06 21:04 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const user = extractUser(action)(state)
sorry to be a stickler, but how we name things is important. 

this function isn't really extracting the user so much as it's preparing the data for the api patch. right? 

So you'd want to call it something that reflects that. Something like `prepareUserPatch` or `prepareUserPatchData` maybe?

2021-07-07 10:20 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +      const mockAction = {
So I'm using mockAction in two different places, I think it make sense it remains a variable

2021-07-07 10:23 UTC, sciphergfx commented on src/modules/User/User.middleware.ts
> +      const user = extractUser(action)(state)
I understand, but as agreed previously, went with 'extractUser', to make our lives easy. I think we spoke about this in a meeting, but happy to change that.

2021-07-07 11:36 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', () => {
there are 3 expects in this test that captures the expectations of this middleware.
```js
      expect(next).toHaveBeenCalledWith(action)
      expect(store.dispatch).toHaveBeenCalledWith(setUser(user))
      expect(mockNotification).toHaveBeenCalled()
```
We've had just one 'it' for most *SuccessFlow app-wide. I think we need to standardise this across

2021-07-07 11:37 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +    it('should correctly handle being called', () => {
I'll break / add more cases on this @cameronolivier

2021-07-10 22:10 UTC, cameronolivier requested changes

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const selectUserFromLoginPayload = pipe(path(['payload', 'data', 'data', 'user']))
None of these need a `pipe`. Pipe is only required if we have more than 1 function - as in we're piping our functions down the line. As these are all single functions, calling the function directly is perfectly ok. 

As these are new functions, they should be named with `extract` not `select` as discussed.

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const selectUserId = pipe(path(['user', 'id']))
This one - should it not be a selector? It looks like it's taking state? Or what data do we pass into it? If we're using it to select the user ID from state, then we should create a selector for it (it is a much-needed selector)

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const extractUserFromUserUpdateSuccess = pipe(path(['payload', 'data', 'data']))
This needs to be tested.

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.utils.ts
> +export const selectUserId = pipe(path(['user', 'id']))
I see we are using it to get the selector out of state - so it is a selector-  and you can then simply use it in the middleware as you currently are.

It'll need to be tested.

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectBiography = createSelector(selectUser, propOr('', 'biography'))
as mentioned below- the `selectId` util should go here.

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/User/User.selector.test.ts
> +  describe('selectBiography ', () => {
I think these are changes set to come in in YOMA-442 as well (but both of these point at develop). 

So, I'll repeat my comment - should use `rootStateFixture()` here, as your state object is being flagged by typescript as it isn't an accurate representation of the expected redux state (it lacks the auth endpoint).

2021-07-10 22:10 UTC, cameronolivier commented on src/modules/About/About.selector.test.ts
> +    it('should handle empty state if props not available', () => {
As mentioned in the other PR comments, we can remove this, and should be properly mocking state comprehensively. See comments on YOMA-442 PR first.

2021-07-11 07:15 UTC, sciphergfx commented on src/components/SocialRegistration/SocialRegistration.tsx
> -  const facebookSignIn = () => {
Tests errors prompted I take these out. SSO PR should fill this changes

2021-07-13 20:14 UTC, cameronolivier submitted a review, later dismissed
All optional changes, and I think 1 question, but happy to approve as it works.

2021-07-13 20:14 UTC, cameronolivier commented on src/modules/About/About.container.tsx
> +    onPatchUserData: (biography: string) => {
OPTIONAL: From a naming pov, I'd say this should reflect where it's being called - so it's an `onSaveAbout` or onUpdateBiography` - something like that. At this level of abstraction, the code is only concerned with doing something when the user clicks to save their about data. Down the line we might change what action we're calling and not touch the user endpoint - or be saving to a biography credential (idk) - my point is that this should reflect what the call to action is addressing in its naming convention.

The action could easily be patchUser (but updateUser is fine too).

2021-07-13 20:14 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const credentials = extractUserFromLoginPayload(action)
credentials is the incorrect term - it should be "user"

2021-07-13 20:14 UTC, cameronolivier commented on src/modules/User/User.selector.ts
> +export const selectUserId = createSelector(selectUser, prop('id'))
OPTIONAL, as it's a small win, but this could simply be `selectId` - as it's part of the user object, would make sense. As is still works though.

2021-07-13 20:14 UTC, cameronolivier commented on src/modules/About/About.tsx
> +const About = ({ navigation, onPatchUserData, biography }: Props) => {
I'm really not happy with the naming conventions used - but won't let that block this going in.

In our About component, we're calling the 'about' text: 
summary (in `summary` and `setSummary`), biography, about, and (to a degree 'userData'). In a single component. So that's not great.

Also the callback functions within a component should be named according to what's happened within the component - not what needs to happen down the line.

At the moment we have the almost awkward convention that in the About component, we've named the callback to update the user's biography `onPatchUserData`, but the actual action we're using to 'patch' the user data is: `updateUser`. 

I think that this should be named something like `onBiographySave`. 

As said - I'm (not super happy) - but ok to let this in as-is considering the code works and it's tested. But we need to be better on these things going forward.

2021-07-14 20:19 UTC, cameronolivier approved these changes, later dismissed
There are issues here. It needs to be fixed at some point. But in the interests of a level of progress, I'm approving as none seem to be bugs. 

We have a circular import that's bothering me though - I think it'll be fixed if we pull the Navigation stuff out of here and import in middleware, but let's keep an eye on it and otherwise tackle that with SSO refactor.

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +  it('should correctly handle being called', () => {
we need a describe for `setUserOnAuthFlow` above here.

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +import { constants as ApiUserConstants, constants as ApiUsersConstants } from '../../api/users'
this is being imported twice as slightly different constants. We need to fix it.

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      Navigation.navigate(HomeNavigationRoutes.Home)
we should pass Navigation in as a dependency as well - otherwise it's going to be hard to mock it

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +  it('should correctly send notification to the user ', () => {
we also need to test that we're navigating correctly.

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.test.ts
> +  it('should correctly send notification to the user ', () => {
let's add a todo here - and we can add when we touch the code at a later point - as we're going to be updating the SSO stuff anyway

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      Navigation.navigate(HomeNavigationRoutes.Home)
but... let's wait if it's working now as we're updating the SSO anyway - maybe add a TODO in the code so we address it next time.

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.types.ts
> +export interface UserPayload {
DON'T DO NOW. (but we should refactor at some point and do this going forward)
let's not do this now - but a better way to do this - in a way that we ensure better type safety is to rather have everything required - and pick the properties that we're updating each time:
```js
export interface UserPayload {
  firstName: string
  lastName: string
  phoneNumber: string
  countryAlpha2: string
  biography: string
}
```
then when we use it:
```js
const onSaveBiography = (biography: Pick<UserPayload, 'biography'>) => ...
```
 [typescript Pick docs](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys)

And only if we ever are updating and aren't sure what exactly we're updating, we could then do something like: 
```js
const onUpdateRandomUserInformation = (user: Partial<UserPayload>) => ... 
```

2021-07-14 20:19 UTC, cameronolivier commented on src/modules/User/User.types.ts
> +export interface UserPayload {
It's not SUPER important right now as EVERYTHING is a string... so it doesn't really matter. but we could also have an empty object (as everything is optional) which isn't what we want.

2021-07-14 20:21 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      Navigation.navigate(HomeNavigationRoutes.Home)
I just realised this isn't part of SSO work. we should add a TODO for this if we don't do it now.

2021-07-17 20:31 UTC, cameronolivier approved these changes, later dismissed

2021-07-19 20:02 UTC, cameronolivier approved these changes

2021-07-19 20:14 UTC, merged