Yoma 437 - refactor(profile) - save edited user profile data - Draft
didx-xyz/yoma-mobile pull request #92
Opened 2021-07-11 15:38 UTC by sciphergfx

## Scope [YOMA-437](https://yomaworld.atlassian.net/browse/YOMA-437)

![](gifSrc)
## Work Done

## Steps to Test

    
## Screenshots

2021-07-12 05:28 UTC, sciphergfx commented on src/modules/Profile/Profile.form.tsx
> +            {/* <Spinner visible={formikHandlers.isSubmitting} /> */}
Visible prop should be from redux, I think it's best tackled on a different ticket.

2021-07-13 20:33 UTC, cameronolivier requested changes
Mostly naming convention issues. Will test the code once this is done.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.container.ts
> +    onPatchUserData: (user: any) => {
as mentioned in the other PR, this should be named according to what we're doing here (so update or saving the user's information - I think we can generally remove 'data' - as 'saveUser' is understood to mean 'save user's data'.

I'm happy to call our actions 'patchUser' instead of 'updateUser', but I think update works fine for now.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.form.tsx
> +            {/* <Spinner visible={formikHandlers.isSubmitting} /> */}
Agreed -all loading states stopped/started by side effects/api calls should be handled within redux.

Any local loading states should be handled internally.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  user: any
why revert on the typing?

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  user: any
if it's only a partial user response, then we could use `Partial<UserResponse>` - but I suspect that UserResponse isn't correct as that's the response from the API, so we should type it out specifically for the fields changing on the Profile form.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  const [userData] = useState<UserResponse>(user)
where possible, let's remove 'data' or 'info' as 9/10 it's superfluous.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  const [userData] = useState<UserResponse>(user)
Also if we never update the `userData`, then it's essentially the same as the `user` prop, so I'm not sure why we would want to create a new variable.

2021-07-13 20:33 UTC, cameronolivier commented on src/modules/User/User.middleware.ts
> +      const patchPayload = extractUserPatchPayload(action.payload)
I'd suggest this be userPayload. 'patch' here says nothing about the data. it's the same as `postPayload` or `getPayload` which means nothing really. 

I think if we remove the 'patch' part altogether across our naming (unless we adopt it in our actions in place of 'update'), it'll really help our naming. 

```js
const user = extractUserfromUpdateUserPayload(action.payload)
```
should be perfectly ok.

2021-07-15 21:04 UTC, cameronolivier reviewed
Going to wait for 450 to be in develop and then I'll give it a run through - happy with things so far.

2021-07-15 21:04 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  const handleProfileForm = () => {
we might need to wrap this in a useCallback - but let's see - as long as we're not getting into any weird ui things we should be ok.

2021-07-17 21:00 UTC, cameronolivier reviewed
Happy with the code, but I tried to upload an image and it failed to open the camera or anything.

2021-07-17 21:02 UTC, cameronolivier submitted a review, later dismissed

2021-07-20 22:29 UTC, cameronolivier approved these changes, later dismissed

2021-07-22 08:53 UTC, cameronolivier approved these changes

2021-07-22 08:58 UTC, merged