Yoma-438 - refactor(Profilee): save new profile image
didx-xyz/yoma-mobile pull request #96
Opened 2021-07-15 02:19 UTC by sciphergfx

## Scope [YOMA-438](https://yomaworld.atlassian.net/browse/YOMA-438)

![](gifSrc)
## Work Done
- Support for profile image upload

2021-07-17 21:07 UTC, cameronolivier requested changes

2021-07-17 21:07 UTC, cameronolivier commented on src/modules/Profile/Profile.tsx
> +  const handleProfilePhoto = () => {
please move this to middleware. 

fire an action to save the image. then handle what you're doing in the util in the middleware - then catch the success and fire the onPhotoSave action.

2021-07-20 16:44 UTC, sciphergfx commented on src/redux/store.ts
> +          userActions.uploadUserPhotoSuccess.type,
form comes with unserialisable values

2021-07-21 21:13 UTC, sciphergfx commented on src/modules/User/User.middleware.test.ts
> +      const capturedProfileImageMock = () =>
Struggling to mock this

2021-07-22 00:36 UTC, merged