YOMA-452 - refactor(Credentials): Experience - save new/edited experience to backend (Draft)
didx-xyz/yoma-mobile pull request #99
Opened 2021-07-20 13:55 UTC by sciphergfx

## Scope [YOMA-XXX](https://yomaworld.atlassian.net/browse/YOMA-XXX)

![](gifSrc)
## Work Done
- Redux setup for credentials module

2021-07-21 22:02 UTC, cameronolivier requested changes

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.test.tsx
> +import { mergeRight } from 'ramda'
there is a Credentials endpoint on swagger - that isn't the same as the UserCredentials - so I don' think it's a good idea to have a module here called Credentials that is the UserCredentials.

I'd suggest moving this back into the User module. 
Alternatively, rename this to UserCredentials module - and then maintain that naming convention throughout.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(UserActions.clearUser())
we should add an action to clearUserCredentials (presuming you're not going to move it back to User module), Organisations and Skills here as well.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +export const setCredentialsFlow: Middleware =
we need to stick to a naming convention - half of these are UserCredentials, the other have is just Credentials. 

considering the above (about there being another credentials endpoint already, I'd adjust all of these to `UserCredentials`.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +export const setCredentialsFlow: Middleware =
(actions included)

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +      const user = extractCredentialsFromHydratePayload(action)
this should be `userCredentials`. If you're going to copy-paste code that's 100% but please make sure to update the naming of your variables to make sense in their new context.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +      const user = extractCredentialsFromHydratePayload(action)
and would be `extractUserCredentials...`

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +export const createCredentialsFlow: Middleware =
this middleware and the next one (updateCredentialsFlow) looks like it's exactly the same - so we probably only need 1 of these.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +    if (updateCredentialsSuccess.match(action)) {
do we not need to handle any of the data coming back with updateCredentialsSuccess - like save it to the store?

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +export const createCredentialsSuccessFlow =
this is the same as updateCredentialsSuccessFlow, so there's some duplication here.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.tsx
> +export const createCredentialsFailureFlow =
likewise - the same as update... failure

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.reducer.tsx
> +  builder.addCase(setCredentials, (state, action) => state.concat(action.payload))
each credential should be storing their own data. 

so Experience should have its own reducer storing the user's experience, which we should be pulling out of the response we get for credentials- so I don't see Credentials itself storing the data. 

This is why I set it up the way I did - we're simply fetching the data - and it's up to each of the modules to extract the data they need from the payload.

Then, I've mentioned it before - but we need to be normalising our data as such: 
https://redux.js.org/usage/structuring-reducers/normalizing-state-shape
And redux toolkit has some great examples: https://redux-toolkit.js.org/usage/usage-guide#managing-normalized-data
I'd suggest we use normalizr library: https://github.com/paularmstrong/normalizr
So for the endpoints where we have lists of data, we want something like this: 
```ts
experience: {
  entities: {
    experienceId1: {....},
    experienceId2:{....},
    ...
  }
 ids: ['experienceId1', 'experienceId2', ...],
}
```

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.types.ts
> +export type QualificationResponsePayload = {
I'd suggest the Qualification items move to the Experience module - presuming that's where they should exist.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.utils.ts
> +export const extractCredentialsFromHydratePayload = path([]) //TODO: add path
I'd think this shoudl rather be named `..FromFetchUserCredentialsPayload`? - because this isn't coming in from the Hydrate payload - but on the Success action for FetchUserCredentials: This one `CredentialsActions.fetchUserCredentials()` -> which should fire `fetchUserCredentialsSuccess` with the payload.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +    qualifications: [],
I'm presuming 'qualifications' == experience items?

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +import { createSelector } from '@reduxjs/toolkit'
as mentioned elsewhere, I think we should have middleware that gets the experience/qualifications out of the credentials payload, normalizes it and stores it in the Experience reducer. 

Then we have an Experience.selector that selects that data from state.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +const mapStateToProps = (state: RootState) => {
you should create a selector file that handles this mapping as we've done elsewhere, then it should just look like: 
```ts
const mapStateToProps = selector
```

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +const mapStateToProps = (state: RootState) => {
this selector should be tested.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +    fetchSkillsList: () => {
current pattern is to prefix callbacks/handlers with 'on' - and to be linked to the component, not what it's doing - currently this is `onExperienceInit` - or something like that - as the callback name, and we can then dispatch both skills and organisations from the single callback.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +    fetchSkillsList: () => {
I actually think we should be loading the skills and organisations on app hydrate already - so not sure how useful it would be to load it again here on component init.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +    fetchSkillsList: () => {
if you keep it here- please make sure it's not doing an api call everytime we navigate to this page. I don't think the data will be changing often - and it's a better user experience if the data is already there - than if the user now has to wait for the orgs or skills list to populate.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  qualifications: [QualificationRequestPayload]
is this correct or should it be `QualificationRequestPayload[]`

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  fetchOrganizationsList,
as above-  these should be a single callback: something like `onExperienceInit` - that then dispatches for both of these (presuming that's still something we want to do) - I'd argue it would be better to fetch these on app hydrate.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  fetchOrganizationsList,
Additionally: we should call onExperienceInit in Experience, not from within the ExperienceForm - and do the data fetching from the parent component and simply pass organisations and skills down into the form - rather than passing multiple callbacks and data between components - it's unnecessary imo.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +  fetchOrganizationsList: () => void
as mentioned above - this component should just expect the skills and organisations data to be available to it. - it shouldn't need  handle fetching the data as well.

This will also clean up your component as you won't need to handle setting this data - as it should simply be available.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.types.ts
> +export type DropDownSkill = {
we're just repeating the same thing here - if all the DropDown types are the same, then we should have a single DropDown type instead of individually replicating the same thing each time.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +} from 'modules/Organisations/Organisations.reducer'
this is the same module - please adjust import to be './Organisations.reducer'

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +import { selectOrganisationsFromPayload } from './Organisations.utils'
`extractOrganisationsFromPayload`

2021-07-21 22:02 UTC, cameronolivier commented on src/redux/store.ts
> +  // whitelist: ['auth', 'user'],
remove

2021-07-21 22:02 UTC, cameronolivier commented on src/redux/middleware.ts
> +import Navigation from 'modules/Navigation'
we've injected Navigation directly into our middleware everywhere else- I'm happy with us taking this stance, as I think it's best to remain consistent as much as possible with dependencies, but then we will need to add a refactor task to update our current middleware to match.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +export const selectSkillsFromPayload = path(['payload', 'data', 'data'])
use `extract` naming convention.

Please remember to add tests.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.types.tsx
> +  id?: string
are these really optional? surely a Skill will have an id?

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.selector.tsx
> +export const selectSkills = (state: RootState) => state.skills
remember to add tests

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +  builder.addCase(setSkills, (state, action) => state.concat(action.payload))
remember to add tests.

Also as mentioned in credentials, please normalise the data - so the state should be an object not an array.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +import { showSimpleMessage } from 'utils/error'
is this the correct import?

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +import { fetchSkills, fetchSkillsFailure, fetchSkillsSuccess, setSkills } from 'modules/Skills/Skills.reducer'
please adjust import to './Skills.reducer'

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.utils.tsx
> +export const selectOrganisationsFromPayload = path(['payload', 'data', 'data'])
`extract...`

and add tests

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +import { fetchSkills, fetchSkillsFailure, fetchSkillsSuccess, setSkills } from 'modules/Skills/Skills.reducer'
remember to add tests

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.types.ts
> +export type OrganisationResponsePayload = {
I'd say this is less the response payload - more just an Organisation, hey? (similar for other places - like skills) - I'm presuming this just represents the Organisation - so it makes sense to call it as such - presuming we're going to be using this as the Organisation in the app

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = []
as other places this should be an object and the data should be normalised.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +  builder.addCase(setOrganisations, (_, action) => action.payload)
reminder to add tests

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Organisations/Organisations.middleware.tsx
> +import {
reminder to add tests

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +import { createSelector } from '@reduxjs/toolkit'
the default selector should collate all the data required by the Experience component -in this case it includes Skills and orgs - so add those here - not in the container.

2021-07-21 22:02 UTC, cameronolivier commented on src/modules/Credentials/Credentials.middleware.test.tsx
> +import { mergeRight } from 'ramda'
obviously need more tests here.

2021-07-21 22:14 UTC, cameronolivier requested changes

2021-07-21 22:14 UTC, cameronolivier commented on src/components/DropDownTags/DropDownTags.tsx
>    const deleteSkill = (tag: string) => setDropdownValue(dropElement(tag, dropDownValue))
considering this is a reusable component called 'DropDownTags' we should remove reference to 'skill' here - probably rename to 'removeTag'? or something?

2021-07-21 22:14 UTC, cameronolivier commented on src/modules/Credentials/Credentials.reducer.tsx
> +import { CredentialRequestPayload } from './Credentials.types'
why the renaming? is Credential incorrect here? are we using it elsewhere? I would consider naming it UserCredential though

2021-07-21 22:14 UTC, cameronolivier commented on src/redux/store.ts
> +  whitelist: ['auth', 'user'],
why are we only persisting this data?

2021-07-21 22:14 UTC, cameronolivier commented on src/redux/reducers.ts
> +  credentials,
please remember to add their types to the RootState type and their initial states to the state fixture.

2021-07-26 06:53 UTC, sciphergfx commented on src/modules/Skills/Skills.selector.tsx
> +export const selectSkills = (state: RootState) => state.skills
Sure

2021-07-26 13:13 UTC, sciphergfx commented on src/modules/Skills/Skills.middleware.tsx
> +import { showSimpleMessage } from 'utils/error'
import { showSimpleMessage } from 'utils/error' ?

2021-07-27 15:23 UTC, sciphergfx commented on src/modules/Experience/ExperienceForm/ExperienceForm.constants.ts
> +  url: 'none',
So I'm not quite sure about the url source and language value

2021-07-27 22:25 UTC, cameronolivier requested changes
I'm about 50% through this, but have a few changes which I thought I'd send through so long.

2021-07-27 22:25 UTC, cameronolivier commented on src/api/qualifications/qualifications.constants.ts
> +  method: ApiMethods.Post,
if this is already the default, you don't really need to restate it here-  can just do this, if there are no overrides:
```ts
export const QUALIFICATIONS_CREATE_CONFIG: Partial<ApiMeta> = QUALIFICATIONS_CONFIG
```

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/App/App.middleware.test.ts
> +import { actions as CredentialsActions } from '../UserCredentials'
I know it's longer. -but could we keep the User prefix : `UserCredentialsActions`.

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(UserActions.clearUser())
duplicate clearUser()

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/App/App.middleware.ts
> +      dispatch(CredentialsActions.fetchUserCredentials())
as mentioned above - should be `UserCredentialsActions`

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +import { QualificationRequestPayload } from 'modules/Qualifications/Qualifications.types'
if you exported  this from the Qualifications index.ts then you could import all from Qualifications in a single import: 
```ts
import { actions as QualificationsActions, types as QualificationsTypes } from 'modules/Qualifications'
```

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +export const selectState = (state: RootState) => state
we don't need a selectState selector - state _is_ state...

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Experience/Experience.selector.tsx
> +export default createSelector(selectState, ({ qualifications, skills, organisations }) => ({
...so this should just be
```ts
export default createSelector((seletQualifications, selectSkills, selectOrganisations) => ({
...
```
Also, you want to create selectors in each module that handle getting the state objects for that module - so qualifications would have a `selectQualifications` selector, etc.

`createSelector` returns a function that takes state and passes it into each of the `selectors`.

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.constants.ts
> +  url: 'none',
we getting this from Gareth?

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +  builder.addCase(clearOrganisations, () => INITIAL_STATE)
not sure it makes a difference - but I think setting action and state helped in a different case - `(_state, _action) => INITIAL_STATE`

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Qualifications/Qualifications.utils.tsx
> +export const extractQualificationsFromPayload = path(['payload', 'data', 'data'])
we're repeating this pattern quite a lot- if this is the default way we get any data out of our payloads, maybe we need a `normalizePayload` function that just does this? Happy to discuss thoughts further.

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/Skills/Skills.middleware.tsx
> +import { showSimpleMessage } from 'utils/error'
yeah -I've since looked at it - just seems a weirdly named import - but it is correct- I think we need to name it better/ refactor it at some point... but ignore for now

2021-07-27 22:25 UTC, cameronolivier commented on src/modules/User/User.reducer.ts
> +  builder.addCase(clearUser, () => INITIAL_STATE)
remember we had a weird issue last time - let's keep an eye on this.

2021-07-27 22:25 UTC, cameronolivier commented on src/utils/error.utils.ts
> +export const extractErrorMessageFromPayload = path(['payload', 'data', 'meta', 'message'])
I think this might be better placed in `Error/Error.utils`

2021-07-28 06:53 UTC, sciphergfx commented on src/modules/App/App.middleware.test.ts
> +import { actions as CredentialsActions } from '../UserCredentials'
missed. that

2021-07-28 06:53 UTC, sciphergfx commented on src/modules/Experience/ExperienceForm/ExperienceForm.constants.ts
> +  url: 'none',
yes

2021-07-28 06:55 UTC, sciphergfx commented on src/utils/error.utils.ts
> +export const extractErrorMessageFromPayload = path(['payload', 'data', 'meta', 'message'])
I agree

2021-07-28 11:54 UTC, sciphergfx commented on src/modules/Experience/Experience.selector.tsx
> +export default createSelector(selectState, ({ qualifications, skills, organisations }) => ({
I see now on the documentation that the function allows for multiple selectors, I'll refactor. Thanks

2021-07-28 12:21 UTC, sciphergfx commented on src/modules/Qualifications/Qualifications.utils.tsx
> +export const extractQualificationsFromPayload = path(['payload', 'data', 'data'])
Added a TODO here

2021-07-28 22:23 UTC, cameronolivier requested changes

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Experience/Experience.tsx
> +  qualifications: []
why do we have the 2 different naming conventions - both experience and qualifications seem to be the same thing -  we should pick one unless there are specific differences - and then stick to them. We shouldn't have a component called Experience, which only has qualifications, on onExperienceSave taking a qualification. It's not ideal.

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            name={'organisationId'}
no need to wrap a string with {} for component props.

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            items={mapToDropDownArray(organisationsList, 'key', 'value')}
just thinking- I think we should adjust the data so that we're running `mapToDropDownArray` - I actually think the best place is in the selector.

The idea with a selector is that it takes whatever data is required from the state and manipulates it so that it's ready for the component. 

I think that if we're doing the mapping of the data `mapToDropDownArray` inside the component-  that is running every time the component reloads - and as we're seeing - that's super expensive with skills. 

So there are probably even better ways to make this faster (with an autocomplete as an example), but as the first port of call - let's move the mapping of the data to what's required in the dropdown (As that's the only place we're using that) - in the selector. so that the organization list and skills etc are already ready for the dropdown data.

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            <DatePicker name={'startTime'} label={t('Start date')} handlers={formikHandlers} />
Again props with `prop='string'` or `prop={not string}`.

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +const OrganisationsReducer = createReducer(INITIAL_STATE, builder => {
should not be PascalCase

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const INITIAL_STATE = [] as any
should this not be something like `Skill[]`? Also I think it would be a good idea to normalise the state data as:

```ts
skills: {
  items: { 
    id1: { ... },
    id2: { ... },
    ....
  },
 itemIds: ['id1', 'id2', ...]
}
```

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Skills/Skills.types.tsx
> +export type Skills = string[]
if the payload seems to be in the shape of
```ts
[{key: '', value: ''}, ...]
```
where do we use Skills as `string[]`? 

and I think it would be worthwhile to type the skills data in state.

2021-07-28 22:23 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +      dispatch(QualificationsActions.createQualifications(qualification))
I'm not sure this is doing the correct thing. I'm presuming that adding experience is something we're adding to the user - which means it should be a patch to the user's credentials, right? 

Also  - a user's experience is added by jobs - not qualifications. 

Qualifications are a separate thing - and that is added by a user's Education (self-attested) and Courses (created by admin). 

So it doesn't seem that qualifications should feature at all in experience.

2021-07-28 22:49 UTC, cameronolivier requested changes

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/Experience/Experience.container.tsx
> +      dispatch(QualificationsActions.createQualifications(qualification))
Also - I think we should be adding (patching) to the user's credentials - so experience (or job) as part of the user's credentials - not up to the global job or qualifications etc endpoint. 

So to that - we need to be careful with our naming of our modules and our state keys - because 'qualifications' (or whathaveyou) for the user won't be the same as all qualifications, obviously.

Our options as I can see it are: 
1 - put all in `user` with subproperties to hold each credential, alongside other user data.
```ts
state: {
  user: {
    name: 'Joe Soap',
    ...
    experience: {
      byId: {
        id1: {...},
        ...
      },
      allIds: ['id1', 'id2', ...]
    }
  }
}
```

2 - in a `userCredentials` key, so pretty much the same as above but with the usercredentials split out
```ts
state: {
  user: {
    name: 'Joe Soap',
    ...
  },
  userCredentials: {
    experience: {
      byId: {
        id1: {...},
        ...
      },
      allIds: ['id1', 'id2', ...]
    }
  }
}
```

3 - each credential in its own state key: 
```ts
state: {
  user: {
    name: 'Joe Soap',
    ...
  },
  userExperience: {
    byId: {
      id1: {...},
      ...
    },
    allIds: ['id1', 'id2', ...]
  },
  userSkills: {
    byId: {
      id1: {...},
      ...
    },
    allIds: ['id1', 'id2', ...]
  },
  ...
}
...
```

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/UserCredentials/UserCredentials.middleware.tsx
> +      dispatch(setUserCredentials(userCredentials))
I don't believe we should be setting this as a single big blob - I was envisioning that each category (experience, skills, etc) would have its own endpoint with normalised data.

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/UserCredentials/UserCredentials.middleware.tsx
> +      dispatch(setUserCredentials(userCredentials))
I have added another comment above around how to go about structuring the user credential data in state (and by extension in our modules). I believe that should inform how we go about doing this. 

I had mentioned something like this in earlier comments on the pr

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/UserCredentials/UserCredentials.test.fixtures.ts
> +export const USER_CREDENTIALS_RESPONSE = [
I don't feel like this is a comprehensive example of the data returned (there's definitely more than just qualifications coming back, surely?

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/UserCredentials/UserCredentials.selector.test.tsx
> +      expect(result).toEqual(state.userCredentials)
This should rather be `USER_CREDENTIALS_RESPONSE` - it's just a little more explicit.

2021-07-28 22:49 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
as we're going to be using INITIAL_STATE for test fixtures and RootState shape, etc  - this needs to be accurate - we can't really be using any here, so please add typing. 

Also as I've mentioned elsewhere, we need to have a normalised data shape.

2021-07-29 07:54 UTC, sciphergfx commented on src/modules/Experience/Experience.tsx
> +  qualifications: []
We have that because We're creating modules as per the collections on the API, i think you mentioned this.

2021-07-29 10:47 UTC, sciphergfx commented on src/modules/Experience/Experience.container.tsx
> +      dispatch(QualificationsActions.createQualifications(qualification))
Thanks @cameronolivier 

I think as discussed in yesterdays meeting the swagger documentation does not align with the shape of request data on the fields presented on the experience form on mobile, hence opting for qualifications which included startTime and endTime fields.

That said, the choice to create a separate module for qualifications (which should be jobs) was to maintain our collections module naming standard which I think you suggested. 
I’e Auth / User / “CREDENTIAL_NAME” / “ANOTHER_CREDENTIAL_NAME” … 

I think most have their own CRUD end points has should ideally have their own reducers, if I’m not mistaken? 
I also think this aligns with our reducer names hence my choice for using “credentials” before refactoring to userCredentials as you once suggested we have - auth, user, skills, ( and possibly “credentials” which maintains a state array of credentials ) etc

I think with regards our state shape suggestions, I do agree with option 2, 

I think given the shape of our credentials response payload.
 // credential types illustrated - challenge and job
[  
    {
      "challenge": {
        "id": "challenge_id",
      }, 
      "id": "credential_id",
    }, 
      {
      "challenge": {
        "id": "challenge_id",
      },
      "id": "credential_id",
    },
     {
      "job": {
        "id": "job_id",
      },
      "id": "credential_id",
    },
  ],

And given this data shape
 experience: {
      byId: {
        id1: {...},
        ...
      },
      allIds: ['id1', 'id2', ...]
    }


My concern is having to maintain an array of ids when we don’t have these objects keyed with IDs, something similar to how Firestore stores it’s collection.

If this approach provides us with a much more efficient way of handling the data in-app and doesn’t add any layer of complexity and boilerplate, happy with it!


As a aside, a suggestion:

I think we can still have a “credentials” module and simply extract all credential by type, with one utility function, then make the data available to the credentials, in this case, “challenge” or “job”.

That said, we have an endpoint for fetching credentials by type, which can update those credential types (challenge / job) states seamlessly as they share the same object type

I.E
 src -> module -> credential -> challenge (also contains reducer/middleware for CRUD ops.)
							-> job (also contains reducer/middleware for CRUD ops.)

This will make it much more easier to handle at the UI level

2021-07-29 10:53 UTC, sciphergfx commented on src/modules/Experience/Experience.tsx
> +  qualifications: []
I agree, as. i mentioned above, was trying to avoid wiring all "qualifications" related stuff to experience directly
. I'll rename onExperienceSave

2021-07-29 10:59 UTC, sciphergfx commented on src/modules/Skills/Skills.types.tsx
> +export type Skills = string[]
I only focused on skills array, which is what's needed for this ticket, I think there's a separate ticket for skills

2021-07-29 11:01 UTC, sciphergfx commented on src/modules/UserCredentials/UserCredentials.test.fixtures.ts
> +export const USER_CREDENTIALS_RESPONSE = [
You're right, but the plan is to handle this on YOMA-451.. I added a TODO to some parts related to this

2021-07-29 11:03 UTC, sciphergfx commented on src/modules/UserCredentials/UserCredentials.middleware.tsx
> +      dispatch(setUserCredentials(userCredentials))
I suggested a approach to handling this above

2021-07-29 11:05 UTC, sciphergfx commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            <DatePicker name={'startTime'} label={t('Start date')} handlers={formikHandlers} />
I think this is allowed,  We have hundreds of it in the code base, but it's a cleaner way to add a string. Do you want me to effect this change on this PR or we create a ticket an effect it everywhere? @cameronolivier

2021-07-29 11:06 UTC, sciphergfx commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            name={'organisationId'}
I think this is allowed,  We have many instances of it around the code base, but it's a cleaner way to add a string. Do you want me to effect this change on this PR or we create a ticket an effect it everywhere? @cameronolivier

2021-07-29 11:06 UTC, sciphergfx commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            <DatePicker name={'startTime'} label={t('Start date')} handlers={formikHandlers} />
Responded to this above

2021-07-29 11:07 UTC, sciphergfx commented on src/modules/Organisations/Organisations.reducer.tsx
> +export const INITIAL_STATE = [] as any
I agree

2021-07-29 11:08 UTC, sciphergfx commented on src/modules/Skills/Skills.reducer.tsx
> +export const INITIAL_STATE = [] as any
this will most likely change when we get to the skills ticket, I added this to hold the array for the experience form

2021-07-29 12:44 UTC, sciphergfx commented on src/modules/Organisations/Organisations.reducer.tsx
> +const OrganisationsReducer = createReducer(INITIAL_STATE, builder => {
You mean the reducer name?

2021-07-29 21:11 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            name={'organisationId'}
weird. it should be caught by linting. It is the pattern we should be sticking to - but refactor when you touch the file - so if you're making changes now, then please fix it up. I don't think we need a separate PR for this.

2021-07-29 21:11 UTC, cameronolivier commented on src/modules/Experience/ExperienceForm/ExperienceForm.tsx
> +            items={mapToDropDownArray(organisationsList, 'key', 'value')}
@sciphergfx  - have you gotten to this?

2021-07-29 21:11 UTC, cameronolivier commented on src/modules/Organisations/Organisations.reducer.tsx
> +const OrganisationsReducer = createReducer(INITIAL_STATE, builder => {
yes

2021-07-29 21:12 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const INITIAL_STATE = [] as any
I think the skills ticket is the skills for the user. But happy so long as we ensure we're updating within the next few weeks.

2021-08-02 20:45 UTC, sciphergfx commented on src/redux/store.ts
> +  blackLists: ['skills'],
Using skills as a search currently, the data is not persisted, and it doesn't need to be cleared as it's temporarily hence removing it on resetAppState. I'll refactor this when I work on the skills ticket.

2021-08-02 21:39 UTC, sciphergfx commented on src/modules/Job/Job.utils.tsx
> +export const prepareJobCredentialPayload =
can use "extract", not sure if it fits well here

2021-08-04 22:49 UTC, cameronolivier requested changes
This should be deleted: `src/modules/Organisations/Organisations.types.tsx` -if it's not already

My expectation of this task was to simply handle saving new or edited experience to the backend. That's it 

you should have split out the other requirements into separate stories or subtasks if needed. 

Handling the data for the UI to enable being able to send should be stories that come before this - that we can PR separately. 

Could you break it up a bit better. I can't review 71 files effectively.

2021-08-04 22:49 UTC, cameronolivier commented on src/modules/Job/Job.selector.tsx
> +export const selectJobTmpFormValues = createSelector(selectJob, path(['tmpFormValues']))
what is this for? why are we storing `tmpFormValues`?

2021-08-04 22:49 UTC, cameronolivier commented on src/components/InfoCard/InfoCard.styles.ts
> +    borderRadius: 50,
Why 50? If we want to create a circular radius, it should be 50% of the width - so set it to IMAGE_SIZE/2 if that is what you want to do. 

you can import `CIRCULAR_RADIUS_DIVISOR` to make it more explicit: 
```ts
borderRadius: IMAGE_SIZE/CIRCULAR_RADIUS_DIVISOR,
```

2021-08-04 22:49 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const dropDownFromArray = (array: string[]) => {
this and the above isn't a string util. Maybe an array util... but I think this and the above should move to the dropdown component - as they're specifically for that purpose.

2021-08-04 22:49 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +export const extractPayloadData = path(['payload', 'data', 'data'])
This wouldn't be a redux util - I'd think it'd be an api util?

2021-08-04 22:49 UTC, cameronolivier commented on src/modules/User/User.types.ts
> +export interface UserCredentialPayload {
is this the 'payload' or is it really just a type for a UserCredential (it seems to be the latter)

2021-08-04 22:49 UTC, cameronolivier commented on src/modules/User/User.reducer.ts
> +export const fetchUserCredentialsSuccess = createAction<any>(`${name} fetchUserCredentialsSuccess`)
Please add a TODO to type this correctly.

2021-08-04 22:49 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const filterSkillsByName = createAction<string>(`${name} filterSkillsByName`)
Do we have Name? - Skills Type is `{ key, value }` -> would it be `byValue`?

2021-08-04 22:49 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const sliceArrayByNumber = (number: Number, array: any[]) => slice(0, number, array)
this is maybe an array util? not a string one. And would probably be splitAtPosition - or splitAt? not byNumber. 

This ramda util does it already though: https://ramdajs.com/docs/#splitAt

2021-08-04 22:49 UTC, cameronolivier commented on src/utils/strings.utils.ts
> +export const searchArrayOfObjByValue = (query: string, array: any[]) =>
the array shouldn't be of any[] - it should be typed to be an object with at least a value property. 
- at which point, is it useful to be generic? 

if we're simply finding and returning values in an array - I think we can add this to Skills as a util - and simply call it something like findSkills. Also, I'm not sure we need to be checking query length here.

2021-08-06 02:07 UTC, sciphergfx commented on src/utils/redux.utils.ts
> +export const extractPayloadData = path(['payload', 'data', 'data'])
sure

2021-08-24 21:09 UTC, cameronolivier requested changes
suggestion: Remember to bump version and release notes.

2021-08-24 21:09 UTC, cameronolivier commented on src/components/DropDownTags/DropDownTags.tsx
> +          if (values[name] !== itemValue) {
Suggestion: I think it might be better to move this to a callback function? I"m not sure how heavy these functions might be? but we're calling 3 and reinstantiating this function on every refresh. What do you think?

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.types.ts
> +export type DropDownList = {
Question: is this not a type shared across multiple components? Surely we have a shared type for this already? 
Suggestion: If not we should create one.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  const renderItem = (item: any) => {
issue: could you type this

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +import { INITIAL_VALUES, MOCK_ORGANISATIONS, MOCK_SKILLS } from './UserJobsForm/UserJobsForm.constants'
issue: we should remove the mock values as by this task (452) everything should be tied up and we should no longer need them. Can delete out of the constants file as well.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  const editUserJob = (item: any) => {
suggestion: I think it might be good to wrap this in a useCallback.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +              skills={MOCK_SKILLS}
we should have skills and orgs wired up to real data as a part of this task.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.tsx
> +            items={mapToDropDownArray(organisationsList, 'key', 'value')}
issue: this mapping for dropdown needs to be happening in the selector, not here.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.tsx
> +            items={mapToDropDownArray(skillsList, 'value', 'value')}
issue: this mapping for dropdown needs to be happening in the selector, not here.

2021-08-24 21:09 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.tsx
> +            items={mapToDropDownArray(skillsList, 'value', 'value')}
this will be re-mapped every time we load this component.

2021-08-26 21:55 UTC, cameronolivier requested changes
a couple of questions and 1 or 2 final updates.

2021-08-26 21:55 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +    return map((id: string | number) => entities[id], defaultIds)
question: why would this be a number? We cannot use numbers as an object key, so I don't think this would every be a number. (if it is we should prefix the number with a string)

2021-08-26 21:55 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.selector.tsx
> +  selectFiltered,
issue: `selectFiltered` doesn't inform that this is for skills. 
We've chosen to keep relatively generic selector names (`selectId` or `selectFiltered`) - but to make this useful, we need to import external selectors as `import * as`...  - ie `import * as OrganisationsSelectors`  & `import * as SkillsSelectors` so that we can use it as `SkillsSelectors.selectFiltered`

2021-08-26 21:55 UTC, cameronolivier commented on src/modules/Skills/Skills.utils.tsx
> +    return map((id: string | number) => entities[id], defaultIds)
Question: If the shape of entities is `{id: {id: 'id', value: 'value'}}`, why are you returning the entity object?

2021-08-28 19:54 UTC, cameronolivier requested changes

2021-08-28 19:54 UTC, cameronolivier commented on src/utils/redux.utils.ts
> +export const extractUserCredentialId = path(['payload', 'data', 'data', 'id'])
suggestion/nitpick: this should be in User module utils, a module specific util (...UserCredential...) should not be in the shared utils.

However you could rename to `extractId` which you already have. 

I'd suggest you use `extractDataFromPayload` and simply get the id from the 
```ts
const data = extractDataFromPayload(action)
return data.id //or however you want to deal with it.
```
I don't think it needs be any more complicated than that.

2021-08-28 19:54 UTC, cameronolivier commented on src/redux/store.ts
> +          JobsActions.createJob.type,
question: what of these require to be excluded? I'm not sure I understand why.

2021-08-28 19:54 UTC, cameronolivier commented on src/redux/store.ts
> +          UserJobsActions.setUserJobsFormValues.type,
issue: we should definitely not be ignoring any `set` actions - we should work around these so that we aren't storing unserialisable data in state - that should never happen. 

The only reason I can see why an error is thrown is that state should only have serialisable data. So currently the app tests all actions - and errors if one doesn't have serialisable data - but for the most part it's fine for us because we're never storing that in state - it's being used within our flows.

So you need to find a way around this without adding this action (or any action tied to a reducer) here.

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.utils.tsx
> +  path(['payload', 'data', 'data']),
1. issue: we already have a util that deals with getting data out of a payload
2. nitpick: 'Job' in `extractUserJobsFromPayload` should be singular if we're only getting 1 job.
3. issue/nitpick: aim to do 1 thing in a function. This function is meant to extract data - don't also cast as an array.

suggestion: 
This util should only care about extracting data out of the data object itself - so we should prepare the data first (extract from payload with `extractDataFromPayload` in `src/util/redux.utils`) and _then_ get what we need from it. Finally, we can cast to array further on in our code - either by calling `of` on it or simply by wrapping it in `[]`.

Rename to: `extractUserJobFromData` (singular 'Job' and extract from data not payload)

```ts
// this util: 
export const extractUserJobFromData = pick([
  'id',
  'verifiedAt',
   ... // all the other properties
  'job',
]),
...

// usage:
const data = extractDataFromPayload(action) // prepare the date by extracting it from the payload
const userJob = extractUserJobFromData(data) // only get the user job from data
const return [userJob] // cast as array
```

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  filterSkillsByValue: (query: string) => void
nitpick: this should be named according to convention
suggestion: something like `onFilterSkills`.

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.tsx
> +  filterSkillsByValue: (value: string) => void
nitpick: this should be named according to convention.
suggestion: something like `onFilterSkills`.

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  const addUserJob = useCallback(() => {
nitpick: should follow convention - `handleAddUserJob`

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.tsx
> +  const editUserJob = useCallback(
nitpick: should follow convention - `handleEditUserJob`

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +      UserActions.fetchUserCredentialsFailure.match(action)
issue/question: why are we catching failure action here and handling it as if it was a success?

2021-08-28 19:54 UTC, cameronolivier commented on src/modules/UserJobs/UserJobs.middleware.ts
> +      const response = extractUserJobsFromPayload(action)
suggestion: as mentioned around the utils, this should be adjusted to a 2-step process, similar to line 49 of this file (above).

```ts
const data = extractDataFromPayload(action)
const job = extractUserJob(data)
const normalisedJobs = normalise([job])
```

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/Experience/Experience.utils.tsx
> +  skillNames: pathOr([], ['job', 'skills']),
Api doesn't include skills array hence using pathOr

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/User/User.types.ts
> +export interface UserCredentialPayload {
there are 2 payloads for userCredentials create/update hence seperating this

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/Job/Job.selector.tsx
> +export const selectJobTmpFormValues = createSelector(selectJob, path(['tmpFormValues']))
We need a way to temporarily store form values needed for credential creation and updates.

2021-08-29 18:12 UTC, sciphergfx commented on src/utils/strings.utils.ts
> +export const dropDownFromArray = (array: string[]) => {
I'll take this out, it was added when I implemented a search API for skills

2021-08-29 18:12 UTC, sciphergfx commented on src/components/DropDownTags/DropDownTags.tsx
> +          if (values[name] !== itemValue) {
the component re-renders when a change is effected, this was a way to ensure it does so when it's values are changed.  It was a fix to the UI issue with dropdown

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.tsx
> +import { INITIAL_VALUES, MOCK_ORGANISATIONS, MOCK_SKILLS } from './UserJobsForm/UserJobsForm.constants'
We need the 2 pending PRs in before this change

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.tsx
> +              skills={MOCK_SKILLS}
replied this above

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/UserJobs/UserJobsForm/UserJobsForm.tsx
> +            items={mapToDropDownArray(organisationsList, 'key', 'value')}
already in

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/Skills/Skills.utils.tsx
> +    return map((id: string | number) => entities[id], defaultIds)
The UI component takes an object hence selector having ```mapToDropDownArray(list, 'value', 'value')```

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.selector.tsx
> +  selectFiltered,
Noted

2021-08-29 18:12 UTC, sciphergfx commented on src/modules/UserJobs/UserJobs.middleware.ts
> +      UserActions.fetchUserCredentialsFailure.match(action)
ah....this should have been a reverted error, missed it sorry

2021-08-29 18:12 UTC, sciphergfx commented on src/redux/store.ts
> +          JobsActions.createJob.type,
I understand this could be better handled but it really doesn't matter since the date string is processed nonetheless. I'll try to check the documentation to see how it can be better approached. As an aside, decided to add this owing to time constraint to get this in.

2021-08-29 18:12 UTC, sciphergfx commented on src/redux/store.ts
> +          UserJobsActions.setUserJobsFormValues.type,
responded above

2021-08-29 21:44 UTC, cameronolivier commented on src/redux/store.ts
> +          JobsActions.createJob.type,
My concern is that it shouldn't be throwing an error if it is only serializable data and we shouldn't be saving anything that isn't serializable - that shouldn't go into state. I doubt that 'createJob' is storing to state - so that's fine it's more the `setUserJobsFormValues` that I think we need to remove (or find how to fix).

2021-08-29 21:52 UTC, cameronolivier requested changes
the `setUserJobsFormValues` is an important thing to fix imo.

2021-08-29 21:52 UTC, cameronolivier commented on src/modules/Skills/Skills.reducer.tsx
> +export const onFilterSkills = createAction<string>(`${name} onFilterSkills`)
sorry if there was a misunderstanding- the action shouldn't be called 'onFilterSkills' - just the callbacks. 
an action can be `filterSkills` or `getFilteredSkills` (by value would be implied, I'd think) -

2021-08-29 21:52 UTC, cameronolivier commented on src/redux/store.ts
> +          UserJobsActions.setUserJobsFormValues.type,
so did I :) - we should make 100% sure that `setUserJobsFormValues` isn't storing anything unserialisable in state and remove it from this ignore list. 

I'm ok with the others for now (but don't want to be just adding things here unless necessary)

2021-09-01 21:22 UTC, cameronolivier approved these changes

2021-09-01 21:22 UTC, merged